// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Hold `asset` open as a bin, answering the header and the rows at depth zero.
	 * 
	 *  With no `entry`, the rows are one per object. With one, `0x` and eight hex digits,
	 *  the rows are that object's properties and the answer carries its header facts.
	 */
	binOpen: (asset: AssetRef, entry: string | null) => __TAURI_INVOKE<({ ok: true; value: BinDocumentHandle }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_open", { asset, entry }),
	/**
	 *  The rows under one node of an open document, `offset` in and at most `limit` of them.
	 * 
	 *  `entry` is the object's hash as `0x` and eight hex digits. `path` is the wire form
	 *  of the property path, empty for the object itself. Every row carries what the meta
	 *  schema declares for its field at the install's build.
	 */
	binChildren: (document: BinDocumentId, entry: string, path: string, offset: number, limit: number) => __TAURI_INVOKE<({ ok: true; value: BinRows }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_children", { document, entry, path, offset, limit }),
	/**  Drop one id. Its asset leaves the store with its last id. */
	binClose: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("bin_close", { document }),
	/**
	 *  One class's fields and their declared kinds at the install's build.
	 * 
	 *  Read out of the meta schema. `None` for a class the schema does not describe.
	 *  `class_hash` is `0x` and eight hex digits.
	 */
	classSchema: (classHash: string) => __TAURI_INVOKE<({ ok: true; value: ClassSchema | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("class_schema", { classHash }),
};

/* Types */
/**
 *  What went wrong, as the fields the frontend translates over.
 * 
 *  The frontend owns every sentence a user reads (ADR-0017), so no variant
 *  carries one. A `detail` is prose from outside the app, such as an OS or
 *  crate error, which the frontend draws as data under a title of its own.
 */
export type AppErrorResponse = 
/**  File system I/O failed. */
{ code: "IO"; detail: string } | 
/**  JSON could not be read or written. */
{ code: "SERIALIZATION"; detail: string } | 
/**  A `.modpkg` could not be processed. */
{ code: "MODPKG"; detail: string } | 
/**  No League of Legends installation is configured. */
{ code: "LEAGUE_NOT_FOUND" } | 
/**  A file or directory path cannot be used. */
{ code: "INVALID_PATH"; path: string } | 
/**  No installed mod has this id. */
{ code: "MOD_NOT_FOUND"; modId: string } | 
/**  Input failed validation. */
{ code: "VALIDATION_FAILED"; detail: string } | 
/**  Internal state was not what the operation needed. */
{ code: "INTERNAL_STATE"; detail: string } | 
/**  A failure with no code of its own. */
{ code: "UNKNOWN"; detail: string } | 
/**  No workshop directory is configured. */
{ code: "WORKSHOP_NOT_CONFIGURED" } | 
/**  No workshop project has this name. */
{ code: "PROJECT_NOT_FOUND"; projectName: string } | 
/**  A workshop project with this name already exists. */
{ code: "PROJECT_ALREADY_EXISTS"; projectName: string } | 
/**  A workshop project could not be packed. */
{ code: "PACK_FAILED"; detail: string } | 
/**  A `.fantome` could not be processed. */
{ code: "FANTOME"; detail: string } | 
/**  A WAD could not be read or built. */
{ code: "WAD"; detail: string } | 
/**
 *  The patcher refused or a start failed. The variant says which.
 * 
 *  One code, not one per [`PatcherError`] variant: the whole error travels,
 *  so a code per variant would put the same discriminant on the wire twice.
 */
{ code: "PATCHER"; error: PatcherError } | 
/**  A ZIP archive could not be processed. */
{ code: "ZIP"; detail: string } | 
/**  The library index was written by a newer app version. */
{ code: "SCHEMA_VERSION_TOO_NEW"; fileVersion: number; maxSupported: number } | 
/**  A workshop operation failed. The variant says which. */
{ code: "WORKSHOP"; error: WorkshopError } | 
/**  A launch failed. The variant says which and carries its remedy's inputs. */
{ code: "LAUNCHER"; error: LauncherError } | 
/**
 *  A hashtable cache operation failed.
 * 
 *  `HashtableError` is not `Serialize`, so the detail is where the
 *  variant's own words ride.
 */
{ code: "HASHTABLE"; detail: string } | 
/**  An asset could not be previewed. */
{ code: "PREVIEW"; detail: string } | 
/**  The bytes are not a bin the toolkit reads. */
{ code: "BIN_UNREADABLE"; detail: string } | 
/**  No open bin document has the id. A close and an eviction both remove one. */
{ code: "BIN_NOT_OPEN" } | 
/**  No node of the open bin has the address. */
{ code: "BIN_NODE_NOT_FOUND"; address: string } | 
/**
 *  An overlay build or analysis failed.
 * 
 *  One code with a category, not one per category: `ltk_overlay::Error`
 *  is `#[non_exhaustive]`, so a new category arrives as
 *  [`OverlayErrorCategory::Other`] rather than as a code the frontend has
 *  never heard of.
 */
{ code: "OVERLAY"; category: OverlayErrorCategory; detail: string } | 
/**  A download was asked for from a domain the trusted providers list omits. */
{ code: "UNTRUSTED_DOMAIN"; domain: string } | 
/**
 *  Something GitHub publishes could not be read. The kind says which
 *  remedy applies, and the feed says what was being read.
 */
{ code: "GITHUB"; feed: GitHubFeed; kind: GitHubErrorKind; detail: string };

/**
 *  Where a previewed asset's bytes come from.
 * 
 *  A reference crosses IPC from the webview, so every path in one is untrusted.
 *  [`read`](Self::read) checks a relative path against the root it belongs to
 *  rather than joining it on, and [`File`](Self::File) is the one variant that
 *  names a path outright.
 */
export type AssetRef = 
/**  A file of one layer of a workshop project. */
{ kind: "layer"; 
/**  The project directory. */
project: string; layer: string; 
/**  Path relative to the layer root, with forward slashes. */
path: string } | 
/**  One chunk of one archive of the installed game. */
{ kind: "gameChunk"; 
/**  A `DATA/FINAL`-relative archive name. */
wad: string; 
/**  The chunk's path hash as 16 lowercase hex digits. */
pathHash: string } | 
/**
 *  Any file on disk, for a preview that belongs to no project.
 * 
 *  Confined to no root, because a file dropped on the window or picked
 *  from a dialog is anywhere. The built-in `asset:` protocol already serves
 *  the whole filesystem to the same webview, so this adds no reach.
 */
{ kind: "file"; path: string };

/**
 *  What an open answers: the id, the header, and the rows at depth zero.
 * 
 *  A file open answers one row per object. An open with an entry answers that object's
 *  properties and its header facts (ADR-0028).
 */
export type BinDocumentHandle = {
	document: BinDocumentId,
	header: BinHeader,
	rows: BinRow[],
	/**  The object the open is over. Absent for a file open. */
	object: BinObjectHeader | null,
};

/**
 *  The id one open of a document is addressed by.
 * 
 *  An id is never reused within a process. A call carrying a closed id fails as
 *  [`BinDocumentError::NotOpen`] and reaches no other document.
 */
export type BinDocumentId = number;

/**  Which kind of bin file a document holds. */
export type BinFileKind = 
/**  A `PROP`: the objects themselves. */
"prop" | 
/**  A `PTCH`: a layer over another bin. */
"patch";

/**  What the header row says about an open bin. */
export type BinHeader = {
	kind: BinFileKind,
	/**  The file version of a `PROP`. A `PTCH` carries none. */
	version: number | null,
	/**  The objects the file declares. For a `PTCH`, the objects it adds. */
	objects: number,
	dependencies: string[],
	/**  The patch records of a `PTCH`. Nothing draws them. */
	patches: number,
	/**  The objects a `PTCH` deletes. */
	deleted: number,
};

/**  The facts an object tab's header draws. "The object tab" in docs/ux/BIN_EDITOR.md. */
export type BinObjectHeader = {
	/**  The object's path hash, `0x` and eight hex digits. */
	entry: string,
	/**  The object's path, or its hex where no table names it. */
	name: string,
	/**  The name is a hash no table names. */
	unnamed: boolean,
	/**  `0x` and eight hex digits. */
	classHash: string,
	/**  The class as the tables name it. Absent where no table does. */
	class: string | null,
	/**  How many properties the object holds. */
	properties: number,
};

/**  One row of the viewer, flat. */
export type BinRow = {
	/**  The object's path hash, `0x` and eight hex digits. */
	entry: string,
	/**  The property path on the wire, every field a hash. Empty for the object itself. */
	path: string,
	/**  The same path for a person. Empty for the object itself. */
	label: string,
	node: RowNode,
	/**  What the row is called: the object's path, the property's name, `[i]` or the key. */
	name: string,
	/**  The name is a hash no table names. */
	unnamed: boolean,
	/**  The value's kind. An object row has none. */
	kind: PropertyKind | null,
	value: BinValue,
	/**
	 *  What the schema declares for the field at the install's build. Absent for an
	 *  object, an element, an entry, and a field the schema has no line for.
	 */
	declared: DeclaredKind | null,
};

/**  A window of rows under one node, and how many there are in all. */
export type BinRows = {
	rows: BinRow[],
	total: number,
};

/**
 *  A row's value, in the shape its widget draws.
 * 
 *  A hash rides beside the name a table gave it. A person reads the name and a Copy
 *  takes the hash.
 */
export type BinValue = { type: "none" } | 
/**  A `Bool` or a `BitBool`. */
{ type: "bool"; value: boolean } | 
/**  Any integer kind, as text. A `U64` does not fit a JSON number. */
{ type: "integer"; text: string } | { type: "float"; value: number | null } | 
/**  Two, three or four components. */
{ type: "vector"; values: (number | null)[] } | 
/**  Sixteen cells, row-major. */
{ type: "matrix"; values: (number | null)[] } | { type: "color"; r: number; g: number; b: number; a: number } | { type: "string"; value: string } | 
/**  `0x` and eight hex digits, and the string behind it where a table names one. */
{ type: "hash"; hash: string; name: string | null } | 
/**  Sixteen hex digits, and the chunk's path where a table names one. */
{ type: "wadChunkLink"; hash: string; path: string | null } | 
/**  `0x` and eight hex digits, and the object's path where a table names one. */
{ type: "objectLink"; hash: string; name: string | null } | 
/**  A `Container` or an `UnorderedContainer`, and the kind of every item. */
{ type: "container"; len: number; itemKind: PropertyKind } | 
/**  A `Struct` with a class, or an `Embedded`. */
{ type: "struct"; classHash: string; class: string | null; len: number } | 
/**  A `Struct` with a class hash of zero. */
{ type: "null" } | 
/**  Whether a value is held, and the kind it is or would be. */
{ type: "optional"; present: boolean; itemKind: PropertyKind } | 
/**  The entries, and the kinds the map declares for its keys and its values. */
{ type: "map"; len: number; keyKind: PropertyKind; valueKind: PropertyKind } | 
/**  A leaf this build has no widget for. */
{ type: "undrawn" };

/**  One class as the class card draws it: its name, and its fields typed at one build. */
export type ClassSchema = {
	/**  The class as the database names it. */
	name: string | null,
	/**
	 *  The content build `declared` is read at: the install's, or the newest the
	 *  database names where the install has none it describes.
	 */
	build: number,
	/**  The named fields first, by name, and the unnamed after them by hash. */
	fields: FieldSchema[],
};

/**  What the schema declares for a field, beside whether the file's kind is that. */
export type DeclaredKind = {
	shape: KindShape,
	/**
	 *  The file's kind is not the declared one, as the Problems rule for a property
	 *  type reads the two.
	 */
	mismatch: boolean,
};

/**  One field's type over one span of builds. */
export type FieldRevision = {
	/**  The first content build the revision holds for. */
	from: number,
	/**  The last content build it holds for, inclusive. Open where absent. */
	to: number | null,
	/**  Absent for a type this build cannot map. */
	shape: KindShape | null,
};

/**  One field of a class: its name, its type at the card's build, and every revision. */
export type FieldSchema = {
	/**  `0x` and eight hex digits. */
	hash: string,
	/**  The field as the database names it. */
	name: string | null,
	/**
	 *  The type at the card's build. Absent where no revision covers the build, and
	 *  where the revision names a type this build cannot map.
	 */
	declared: KindShape | null,
	/**  Oldest first. */
	revisions: FieldRevision[],
};

/**  Which way a read of GitHub failed, as the remedy it has. */
export type GitHubErrorKind = 
/**  GitHub was never reached. Waiting for a connection is the remedy. */
"OFFLINE" | 
/**  The address has spent its unauthenticated quota. Waiting is the remedy. */
"RATE_LIMITED" | 
/**  The request went out and what came back is not what was asked for. */
"HTTP";

/**  Which of the things GitHub publishes a read was after. */
export type GitHubFeed = "RELEASES" | "ANNOUNCEMENTS" | "NOTICES";

/**  Which stage of a start failed, for [`PatcherError::InjectionFailed`]. */
export type InjectionStage = 
/**
 *  The host process never came up - it could not be spawned, configured, or
 *  told to start. Antivirus, a missing binary or a declined UAC prompt are
 *  the usual causes, so diagnostics are the useful response.
 */
"HOST" | 
/**  The host ran, but the game was never patched. */
"INJECTION";

/**
 *  A type as the tag composes it: the kind, a `Map`'s key, and what a container holds.
 * 
 *  The wire form of [`Shape`]. A row's tag and a card's field draw it as `list[embed]`
 *  or `map[hash,string]`.
 */
export type KindShape = {
	kind: PropertyKind,
	/**  A `Map`'s key kind. */
	key: PropertyKind | null,
	/**  What an `Option`, a list or a `Map` holds. */
	value: PropertyKind | null,
};

/**
 *  Why a launch request could not be delivered.
 * 
 *  Each variant has a different remedy ("set your game path", "open the Riot
 *  Client"), so each gets its own `ErrorCode` in the shell rather than sharing
 *  one with a discriminating field.
 */
export type LauncherError = 
/**
 *  No `RiotClientInstalls.json`, or nothing in it resolves to an exe on
 *  disk.
 */
{ kind: "RIOT_CLIENT_NOT_FOUND"; installsPath: string } | 
/**
 *  A client is alive and holding the lockfile, but never answered that it
 *  took the launch args. Cold-starting over it would terminate the user's
 *  session, so this is terminal.
 */
{ kind: "RIOT_CLIENT_UNREACHABLE"; reason: string } | 
/**
 *  The client understood the request and refused it - the Terms of Service
 *  are unaccepted, the game is out of date, the patchline is locked. The
 *  remedy is always something the player does in the Riot Client itself,
 *  and `riot_error_code` is Riot's own machine-readable tag for which one.
 */
{ kind: "REFUSED"; riotErrorCode: string; message: string } | 
/**
 *  The user called the launch off while it was waiting.
 * 
 *  Nothing failed, so nothing may be shown as a failure - a toast saying
 *  the launch broke, behind a Cancel button the user just pressed, is the
 *  one outcome this variant exists to prevent. Stopping abandons the wait
 *  and not the launch: a request the client already accepted still starts
 *  a game.
 */
{ kind: "STOPPED" } | 
/**
 *  The launcher was built with something it cannot use. A bug here rather
 *  than a condition the user can clear.
 */
{ kind: "MISCONFIGURED"; reason: string } | 
/**  `RiotClientServices.exe` could not be spawned. */
{ kind: "SPAWN_FAILED"; reason: string } | { kind: "UNSUPPORTED_PLATFORM" } | 
/**
 *  A failure this build of the manager does not know, from a newer
 *  [`ritoclient`], carrying that error's own prose.
 */
{ kind: "OTHER"; message: string };

/**
 *  Which way an overlay build failed, as the remedy a consumer picks between.
 * 
 *  Mirrors the categories of `ltk_overlay::Error`, which is not `Serialize`,
 *  so records and IPC responses carry this while the detail stays in the
 *  message.
 */
export type OverlayErrorCategory = 
/**  The game installation cannot be used. Point the user at their game dir. */
"GAME_DIR" | 
/**  A mod's content could not be used. Blame the mod, not the game. */
"MOD_CONTENT" | 
/**  The output would exceed a WAD format limit. Splitting a mod helps. */
"WAD_LIMIT" | 
/**  A game file is not what its own metadata says. A repair may help. */
"CORRUPT" | 
/**  An `ltk_overlay` invariant broke. Nothing the user did; report it. */
"BUG" | 
/**  An IO, parse or archive failure with no category of its own. */
"OTHER";

/**
 *  Domain errors specific to the patcher.
 * 
 *  Sent over IPC as the `context` payload of an `AppError` with code `PATCHER`.
 *  Frontend code can switch on `kind` to handle each variant.
 */
export type PatcherError = 
/**
 *  Something that mutates the mod library was rejected because a session is
 *  live and pointed at the very files it would rewrite. The caller has to
 *  stop the patcher first - unlike [`Self::AlreadyRunning`], this is not a
 *  stale-status problem.
 */
{ kind: "BUSY" } | 
/**
 *  A start was requested while a session is already live. Benign: it usually
 *  just means the caller's view of the status is stale.
 */
{ kind: "ALREADY_RUNNING" } | 
/**  A stop was requested while nothing was running. */
{ kind: "NOT_RUNNING" } | { kind: "UNSUPPORTED_PLATFORM" } | 
/**
 *  One injection session failed. `stage` separates a host that never came up
 *  from a game that was never patched, since they call for different advice.
 */
{ kind: "INJECTION_FAILED"; stage: InjectionStage; message: string };

/**
 *  The 27 kinds `ltk_meta` reads, as they cross IPC.
 * 
 *  A mirror of [`Kind`], spelled in ritobin's words. The spelling is the tag a row
 *  draws and the word a Problems finding writes. An upstream rename or addition is a
 *  compile error here.
 */
export type PropertyKind = "none" | "bool" | "i8" | "u8" | "i16" | "u16" | "i32" | "u32" | "i64" | "u64" | "f32" | "vec2" | "vec3" | "vec4" | "mtx44" | "rgba" | "string" | "hash" | "file" | "list" | "list2" | "pointer" | "embed" | "link" | "option" | "map" | "flag";

/**  Where a row sits in the tree. */
export type RowNode = 
/**  An object of the file. */
"object" | 
/**  A property of an object, a struct or an embedded. */
"property" | 
/**  One element of a container, or the value of a present optional. */
"element" | 
/**  One entry of a map. */
"entry";

/**
 *  Domain errors specific to workshop operations.
 * 
 *  Sent over IPC as the `context` payload of an `AppError` with code `WORKSHOP`.
 *  Frontend code can switch on `kind` to handle each variant.
 */
export type WorkshopError = 
/**  One or more files already exist in the target layer directory. */
{ kind: "LAYER_FILE_CONFLICT"; conflicts: string[] };

