// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KindShape } from "./KindShape";

/**
 * One field Add property offers for a holder.
 */
export type AddableField = { 
/**
 * `0x` and eight hex digits.
 */
hash: string, name: string | null, shape: KindShape, 
/**
 * What an embed or a pointer holds, or what a list's items hold, as `0x` and hex.
 */
classHash: string | null, class: string | null, 
/**
 * The class declaring the field, where it is a base of the holder's class.
 */
inheritedFrom: string | null, };
