// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddableField } from "./AddableField";

/**
 * What Add property offers for one holder.
 */
export type AddableFields = { 
/**
 * The holder's class, `0x` and eight hex digits.
 */
classHash: string, class: string | null, 
/**
 * The fields the class and its bases declare that the holder does not write. Empty
 * for a class the schema does not describe.
 */
fields: Array<AddableField>, };
