// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { GraphClip } from "./GraphClip";
import type { Mask } from "./Mask";
import type { SyncGroup } from "./SyncGroup";
import type { Track } from "./Track";

/**
 * An animation graph, as a clip table and a viewport read it.
 *
 * "The model" in docs/plans/animation-graph-table.md. Every list keeps the order its
 * map holds, and every key is named by the tables or written as its hex.
 */
export type AnimationGraph = { 
/**
 * The linked file declaring the graph, and none where the open document does.
 */
source: AssetRef | null, 
/**
 * `mClipDataMap`.
 */
clips: Array<GraphClip>, 
/**
 * `mTrackDataMap`.
 */
tracks: Array<Track>, 
/**
 * `mMaskDataMap`.
 */
masks: Array<Mask>, 
/**
 * `mSyncGroupDataMap`.
 */
syncGroups: Array<SyncGroup>, };
