// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One post in the Announcements category.
 */
export type Announcement = { 
/**
 * The feed's own id for the post.
 */
id: string, title: string, 
/**
 * The post's page on GitHub.
 */
url: string, 
/**
 * RFC 3339, as GitHub publishes it, or `None` for an entry without one.
 */
publishedAt: string | null, };
