// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditRejection } from "./EditRejection";
import type { GitHubErrorKind } from "./GitHubErrorKind";
import type { GitHubFeed } from "./GitHubFeed";
import type { LauncherError } from "./LauncherError";
import type { OverlayErrorCategory } from "./OverlayErrorCategory";
import type { PatcherError } from "./PatcherError";
import type { ReadOnly } from "./ReadOnly";
import type { WorkshopError } from "./WorkshopError";

/**
 * What went wrong, as the fields the frontend translates over.
 *
 * The frontend owns every sentence a user reads (ADR-0017), so no variant
 * carries one. A `detail` is prose from outside the app, such as an OS or
 * crate error, which the frontend draws as data under a title of its own.
 */
export type AppError = { "code": "IO", detail: string, } | { "code": "SERIALIZATION", detail: string, } | { "code": "MODPKG", detail: string, } | { "code": "LEAGUE_NOT_FOUND" } | { "code": "INVALID_PATH", path: string, } | { "code": "MOD_NOT_FOUND", modId: string, } | { "code": "VALIDATION_FAILED", detail: string, } | { "code": "INTERNAL_STATE", detail: string, } | { "code": "UNKNOWN", detail: string, } | { "code": "WORKSHOP_NOT_CONFIGURED" } | { "code": "PROJECT_NOT_FOUND", projectName: string, } | { "code": "PROJECT_ALREADY_EXISTS", projectName: string, } | { "code": "PACK_FAILED", detail: string, } | { "code": "FANTOME", detail: string, } | { "code": "WAD", detail: string, } | { "code": "PATCHER", error: PatcherError, } | { "code": "ZIP", detail: string, } | { "code": "SCHEMA_VERSION_TOO_NEW", fileVersion: number, maxSupported: number, } | { "code": "WORKSHOP", error: WorkshopError, } | { "code": "LAUNCHER", error: LauncherError, } | { "code": "HASHTABLE", detail: string, } | { "code": "PREVIEW", detail: string, } | { "code": "BIN_UNREADABLE", detail: string, } | { "code": "BIN_NOT_OPEN" } | { "code": "BIN_NODE_NOT_FOUND", address: string, } | { "code": "BIN_READ_TOO_WIDE", rows: number, cap: number, } | { "code": "BIN_READ_TOO_LARGE" } | { "code": "BIN_READ_TOO_DEEP" } | { "code": "BIN_READ_ONLY", gate: ReadOnly, } | { "code": "BIN_EDIT_REJECTED", address: string, rejection: EditRejection, } | { "code": "BIN_CHANGED_ON_DISK" } | { "code": "BIN_UNWRITABLE", detail: string, } | { "code": "OVERLAY", category: OverlayErrorCategory, detail: string, } | { "code": "UNTRUSTED_DOMAIN", domain: string, } | { "code": "GITHUB", feed: GitHubFeed, kind: GitHubErrorKind, detail: string, };
