// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One vertex attribute the vertex shader reads.
 */
export type Attribute = { 
/**
 * The semantic without its index: `POSITION`, `BLENDINDICES`.
 */
semantic: string, index: number, 
/**
 * The GLSL attribute name.
 */
glslName: string, 
/**
 * Which of `xyzw` the shader reads, as a four-bit mask.
 */
mask: number, };
