// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which champions show their base skin on every skin, a mod's where one replaces it.
 */
export type BaseSkinsScope = "off" | "moddedChampions" | "allChampions";
