// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

/**
 * One property or object that differs from the baseline.
 */
export type BinChange = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The property's wire path under the object, and empty for the object itself.
 */
path: string, kind: ChangeKind, };
