// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The id an open document is addressed by.
 *
 * An id is never reused within a process. A call carrying a closed document's id fails
 * as [`BinDocumentError::NotOpen`] and reaches no other document.
 */
export type BinDocumentId = number;
