// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { BinDocumentId } from "./BinDocumentId";
import type { BinHeader } from "./BinHeader";
import type { BinObjectHeader } from "./BinObjectHeader";
import type { BinRow } from "./BinRow";
import type { DeclaredState } from "./DeclaredState";
import type { ReadOnly } from "./ReadOnly";
import type { SandboxRef } from "./SandboxRef";

/**
 * What an open answers: the id, the header, and the rows at depth zero.
 *
 * A file open answers one row per object. An open with an entry answers that object's
 * properties and its header facts (ADR-0028).
 */
export type BinDocumentHandle = { document: BinDocumentId, 
/**
 * The sandbox the document is held in. ADR-0056.
 */
sandbox: SandboxRef, 
/**
 * The file the document was read from, and the file a save writes.
 *
 * Usually the asset the open asked for. When the open asked for a game chunk that a
 * layer of the sandbox ships, this is that layer's file instead. ADR-0056.
 */
asset: AssetRef, header: BinHeader, rows: Array<BinRow>, 
/**
 * The object the open is over. Absent for a file open.
 */
object: BinObjectHeader | null, 
/**
 * The gate a read-only document stands behind. Absent where it takes edits.
 */
readOnly: ReadOnly | null, 
/**
 * What a declared document says beside its rows. Absent for every other document.
 */
declared: DeclaredState | null, };
