// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinDocumentId } from "./BinDocumentId";
import type { BinHeader } from "./BinHeader";
import type { BinObjectHeader } from "./BinObjectHeader";
import type { BinRow } from "./BinRow";
import type { DeclaredState } from "./DeclaredState";
import type { ReadOnly } from "./ReadOnly";

/**
 * What an open answers: the id, the header, and the rows at depth zero.
 *
 * A file open answers one row per object. An open with an entry answers that object's
 * properties and its header facts (ADR-0028).
 */
export type BinDocumentHandle = { document: BinDocumentId, header: BinHeader, rows: Array<BinRow>, 
/**
 * The object the open is over. Absent for a file open.
 */
object: BinObjectHeader | null, 
/**
 * The gate a read-only document stands behind. Absent where it takes edits.
 */
readOnly: ReadOnly | null, 
/**
 * What a declared document says beside its rows. Absent for every other document.
 */
declared: DeclaredState | null, };
