// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinDocumentId } from "./BinDocumentId";
import type { BinHeader } from "./BinHeader";
import type { BinRow } from "./BinRow";

/**
 * What an open answers: the id, the header, and the root rows.
 */
export type BinDocumentHandle = { document: BinDocumentId, header: BinHeader, rows: Array<BinRow>, };
