// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of bin file a document holds.
 */
export type BinFileKind = "prop" | "patch";
