// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row a search matched, with the path a reveal opens down to.
 */
export type BinFindHit = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The row's property path on the wire. Empty for an object row.
 */
path: string, 
/**
 * The same path for a person. Empty for an object row.
 */
label: string, 
/**
 * The object's path, or its hash where no table names it.
 */
object: string, 
/**
 * What the row is called: the object's path, the property's name, `[i]` or the key.
 */
name: string, 
/**
 * Byte offsets into `name` the query matched. Empty where the value matched alone.
 */
ranges: Array<[number, number]>, 
/**
 * The row's value as one line of text, where it reads as one.
 */
value: string | null, };
