// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinFindHit } from "./BinFindHit";

/**
 * What one search of an open document found.
 */
export type BinFindResult = { 
/**
 * The matching rows in tree order, at most `FIND_ROWS`.
 */
hits: Array<BinFindHit>, 
/**
 * How many rows matched in all, counted on past the cap.
 */
total: number, };
