// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The facts an object tab's header draws. "The object tab" in docs/ux/BIN_EDITOR.md.
 */
export type BinObjectHeader = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The object's path, or its hex where no table names it.
 */
name: string, unnamed: boolean, 
/**
 * `0x` and eight hex digits.
 */
classHash: string, class: string | null, 
/**
 * How many properties the object holds.
 */
properties: number, };
