// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinRow } from "./BinRow";

/**
 * A window of rows under one node, and how many there are in all.
 */
export type BinRows = { rows: Array<BinRow>, total: number, };
