// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinValue } from "./BinValue";
import type { DeclaredKind } from "./DeclaredKind";
import type { PropertyKind } from "./PropertyKind";
import type { RowNode } from "./RowNode";

/**
 * One row of the viewer, flat.
 */
export type BinRow = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The property path on the wire, every field a hash. Empty for the object itself,
 * and `#` then the record's position under a patch target (ADR-0041).
 */
path: string, 
/**
 * The same path for a person. Empty for the object itself, and the record's own path
 * first under a patch record.
 */
label: string, node: RowNode, 
/**
 * What the row is called: the object's path, the property's name, `[i]` or the key.
 */
name: string, 
/**
 * The name is a hash no table names.
 */
unnamed: boolean, 
/**
 * The value's kind. An object row and a target row have none.
 */
kind: PropertyKind | null, value: BinValue, 
/**
 * What the schema declares for the field at the install's build. Absent for an
 * object, an element, an entry, and a field the schema has no line for.
 */
declared: DeclaredKind | null, };
