// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyKind } from "./PropertyKind";

/**
 * A row's value, in the shape its widget draws.
 *
 * A hash rides beside the name a table gave it. A person reads the name and a Copy
 * takes the hash.
 */
export type BinValue = { "type": "none" } | { "type": "bool", value: boolean, } | { "type": "integer", text: string, } | { "type": "float", value: number, } | { "type": "vector", values: Array<number>, } | { "type": "matrix", values: Array<number>, } | { "type": "color", r: number, g: number, b: number, a: number, } | { "type": "string", value: string, } | { "type": "hash", hash: string, name: string | null, } | { "type": "wadChunkLink", hash: string, path: string | null, } | { "type": "objectLink", hash: string, name: string | null, } | { "type": "container", len: number, itemKind: PropertyKind, } | { "type": "struct", classHash: string, class: string | null, len: number, } | { "type": "null" } | { "type": "optional", present: boolean, itemKind: PropertyKind, } | { "type": "map", len: number, keyKind: PropertyKind, valueKind: PropertyKind, } | { "type": "undrawn" };
