// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side of the pair a pass blends by, a `StaticMaterialPassDef::BlendFactor`.
 */
export type BlendFactor = "zero" | "one" | "srcColor" | "oneMinusSrcColor" | "dstColor" | "oneMinusDstColor" | "srcAlpha" | "oneMinusSrcAlpha";
