// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberScalar } from "./MemberScalar";

/**
 * One member of a uniform block.
 */
export type BlockMember = { name: string, 
/**
 * The byte offset in the buffer.
 */
offset: number, size: number, 
/**
 * Whether this permutation reads it. An unread member is compiled out and is no
 * warning when a material writes it.
 */
used: boolean, scalar: MemberScalar, 
/**
 * Rows for a matrix, one otherwise.
 */
rows: number, 
/**
 * Columns for a matrix or vector, one for a scalar.
 */
columns: number, 
/**
 * Array length, or zero for no array.
 */
elements: number, 
/**
 * Whether a matrix is stored a row per `vec4`, which is how D3D packs a `float4x4`.
 */
rowMajor: boolean, };
