// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The built-in mods a user turned on, every one off by default.
 */
export type BuiltinMods = { 
/**
 * Every ward shows its own base skin.
 */
defaultWardSkins: boolean, };
