// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseSkinsScope } from "./BaseSkinsScope";

/**
 * The built-in mods a user turned on, every one off by default.
 */
export type BuiltinModSettings = { 
/**
 * Every ward shows its own base skin.
 */
defaultWardSkins: boolean, 
/**
 * Which champions show their base skin on every skin.
 */
baseSkins: BaseSkinsScope, };
