// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a document's rows are compared with.
 */
export type ChangeBaseline = "opened" | "game";
