// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { SpellCatalog } from "./SpellCatalog";

/**
 * The character spell catalog and the index state supplying it.
 */
export type CharacterSpells = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready" } & SpellCatalog;
