// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectDeclaration } from "./ObjectDeclaration";

/**
 * One named spell and every file declaring its object.
 */
export type CharacterSpell = { 
/**
 * The object's path hash, as `0x` and eight hex digits.
 */
objectHash: string, 
/**
 * The resolved object path.
 */
path: string, 
/**
 * The path below `Characters/{character}/Spells`.
 */
name: string, 
/**
 * The first nested segment, which suggests a group without implying cast order.
 */
group: string | null, 
/**
 * Every declaration, including conflicting classes, in archive order.
 */
declarations: Array<ObjectDeclaration>, };
