// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chunk whose container claimed a checksum its own bytes do not have.
 *
 * The hashes are hex strings rather than numbers because they are 64-bit
 * values, which JavaScript numbers cannot carry exactly.
 */
export type ChecksumMismatchInfo = { 
/**
 * Library mod id (matches `InstalledMod.id` on the frontend).
 */
modId: string, 
/**
 * The mod's WAD target the chunk was read from, e.g. `Aatrox.wad.client`.
 */
wadName: string, 
/**
 * Path hash of the chunk that disagreed, as 16 hex digits.
 */
pathHash: string, 
/**
 * What the container's own TOC claimed, as 16 hex digits.
 */
claimed: string, 
/**
 * What the bytes actually hash to - the value the overlay carries - as
 * 16 hex digits.
 */
computed: string, };
