// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HexBinHash } from "./HexBinHash";

/**
 * A class as a card names it.
 */
export type ClassRef = { hash: HexBinHash, 
/**
 * The class as the database names it.
 */
name: string | null, };
