// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * How many objects of the install declare a class, given the slot the index is in.
 */
export type ClassObjectCount = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready", count: number, };
