// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One class a class line offers.
 */
export type ClassChoice = { 
/**
 * `0x` and eight hex digits.
 */
hash: string, name: string | null, 
/**
 * An item of the holder holds the class already.
 */
held: boolean, 
/**
 * The class the schema declares for the holder, where this one derives from it.
 */
derivesFrom: string | null, };
