// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";

/**
 * One entry of `mEventDataMap`, of any kind of `BaseEventData`.
 */
export type ClipEvent = { 
/**
 * The event's key as the tables name it, and its hash where none does.
 */
name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The event's class as the tables name it, and its hash where none does.
 */
class: string, 
/**
 * `mStartFrame`, the frame of the clip the event fires on.
 */
startFrame: number, 
/**
 * `mEndFrame`, and none for an event that ends on its own, which the meta writes as -1.
 */
endFrame: number | null, 
/**
 * What the event does, for the kinds a viewport plays.
 */
kind: EventKind, };
