// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one `.anm` says about itself: its rate and its length.
 */
export type ClipHeader = { 
/**
 * Frames per second the clip was authored at.
 */
fps: number, 
/**
 * Seconds one pass of the clip lasts.
 */
duration: number, };
