// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One object a layer's `.bin` declares.
 */
export type ContentObject = { 
/**
 * The object's path hash, as `0x` and eight hex digits.
 */
objectHash: string, 
/**
 * The object's path, or its hash when no table names it.
 */
path: string, 
/**
 * The class the object declares, or its hash when no table names it.
 */
class: string, 
/**
 * The class hash, as `0x` and eight hex digits.
 */
classHash: string, };
