// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many problems a run holds at each severity.
 */
export type Counts = { fatals: number, errors: number, warnings: number, infos: number, };
