// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectDeclaration } from "./ObjectDeclaration";

/**
 * Every declaration of one object, with the path they share.
 */
export type DeclaredObject = { 
/**
 * The object's path, or its hash when no table names it.
 */
path: string, 
/**
 * In archive order, and in the game index's tree order within one archive.
 */
declarations: Array<ObjectDeclaration>, };
