// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredMark } from "./DeclaredMark";

/**
 * What a declared document says beside its rows.
 */
export type DeclaredState = { 
/**
 * The layer an edit writes to.
 */
layer: string, 
/**
 * The project's layers in build order.
 */
layers: Array<string>, 
/**
 * The rows a declaration of `layer` touches.
 */
marks: Array<DeclaredMark>, };
