// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { DeclaredObject } from "./DeclaredObject";

/**
 * What the index holds for a set of object hashes, given the slot the index is in.
 */
export type DeclaredObjects = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready", objects: { [key in string]: DeclaredObject }, };
