// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredObject } from "./DeclaredObject";
import type { ObjectIndexStatus } from "./ObjectIndexStatus";

/**
 * What declares each of a set of object hashes, beside the slot the index is in.
 */
export type DeclaredObjects = { 
/**
 * Off `Ready`, only the open document's own objects are in `objects`.
 */
index: ObjectIndexStatus, 
/**
 * By the object's hash, `0x` and eight hex digits. A hash nothing declares is absent.
 */
objects: { [key in string]: DeclaredObject }, };
