// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredSign } from "./DeclaredSign";

/**
 * One row a declaration of the chosen layer touches.
 */
export type DeclaredMark = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, 
/**
 * The row's path on the wire. Empty where the declared path reaches no row.
 */
path: string, sign: DeclaredSign, 
/**
 * The game's value as a declaration spells it. Absent where the game holds none, and
 * for a value that does not render.
 */
game: string | null, };
