// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KindShape } from "./KindShape";

/**
 * What the schema declares for a field, beside whether the file's kind is that.
 */
export type DeclaredKind = { shape: KindShape, 
/**
 * The file's kind is not the declared one, as the Problems rule for a property
 * type reads the two.
 */
mismatch: boolean, };
