// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed representation of a `ltk://settings` deep-link URL.
 */
export type DeepLinkSettingsRequest = { 
/**
 * The public setting or group id the page opens on, as `?focus=` carries it.
 */
focus: string, };
