// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeepLinkInstallRequest } from "./DeepLinkInstallRequest";
import type { DeepLinkSettingsRequest } from "./DeepLinkSettingsRequest";

/**
 * A `ltk://` deep link, as the route named in it.
 */
export type DeepLinkRequest = { "kind": "install" } & DeepLinkInstallRequest | { "kind": "settings" } & DeepLinkSettingsRequest;
