// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed representation of a `ltk://install` deep-link URL.
 */
export type DeepLinkInstallRequest = { url: string, name: string | null, author: string | null, source: string | null, 
/**
 * The host outside the allowlist, or `None` where the allowlist covers it.
 *
 * Stamped by [`handle_single`] rather than by parsing, since the trust is a
 * property of the reader's settings and not of the URL.
 */
untrustedDomain: string | null, };
