// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields to change on a mod's metadata. `None` leaves a field untouched.
 */
export type EditModMetadataArgs = { displayName: string | null, tags: Array<string> | null, champions: Array<string> | null, maps: Array<string> | null, setThumbnailPath: string | null, removeThumbnail: boolean | null, };
