// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";

/**
 * One key of the skin's resolver, and the system it stands for.
 */
export type EffectSystem = { 
/**
 * The key, `0x` and eight hex digits.
 */
key: string, 
/**
 * The `VfxSystemDefinitionData` object, `0x` and eight hex digits.
 */
system: string, 
/**
 * The linked file declaring the system, and none where the skin's own document does.
 */
source: AssetRef | null, };
