// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashRef } from "./HashRef";

/**
 * One pair of a particle event: the joint the system rides, and the joint it aims at.
 */
export type EventSpawn = { 
/**
 * `mBoneName`, and none for a pair riding the skeleton's own origin.
 */
bone: HashRef | null, 
/**
 * `mTargetBoneName`, and none for a pair aiming at nothing.
 */
targetBone: HashRef | null, };
