// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSpawn } from "./EventSpawn";
import type { HashRef } from "./HashRef";
import type { KeyRef } from "./KeyRef";

/**
 * What a clip event does, for the kinds a viewport plays, and nothing for the rest.
 */
export type EventKind = { "kind": "submeshVisibility", 
/**
 * `mShowSubmeshList`.
 */
show: Array<HashRef>, 
/**
 * `mHideSubmeshList`.
 */
hide: Array<HashRef>, } | { "kind": "particle", 
/**
 * `mEffectKey`, `0x` and eight hex digits, which the skin's resolver maps.
 */
effectKey: string, 
/**
 * `mEffectName`, what the author called it.
 */
effectName: string, 
/**
 * `mParticleEventDataPairList`, one spawn per pair.
 */
spawns: Array<EventSpawn>, 
/**
 * `mIsLoop`.
 */
isLoop: boolean, 
/**
 * `mIsKillEvent`, which stops the effect of the key rather than spawning one.
 */
isKill: boolean, 
/**
 * `scale`, which the meta defaults to one.
 */
scale: number, } | { "kind": "jointSnap", 
/**
 * `mJointNameToOverride`, the joint moved, and none for an event naming no joint.
 */
joint: HashRef | null, 
/**
 * `mJointNameToSnapTo`, the joint it stands on, and none for an event naming no joint.
 */
snapTo: HashRef | null, 
/**
 * `offset`, in the frame of the joint stood on.
 */
offset: [number, number, number], } | { "kind": "conformToPath", 
/**
 * `mMaskDataName`, the joints that conform, and none for an event naming no mask.
 */
mask: KeyRef | null, 
/**
 * `mBlendInTime`, seconds the conforming eases in over.
 */
blendIn: number, 
/**
 * `mBlendOutTime`, seconds it eases out over.
 */
blendOut: number, } | { "kind": "other" };
