// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an extract does about a file already sitting where one would land.
 */
export type ExistingFiles = "skip" | "replace";
