// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the library's mods an export writes.
 *
 * Every profile holds every mod, so the only scope narrower than the library
 * is what the active profile has switched on.
 */
export type ExportScope = "enabled" | "all";
