// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an export wrote, and what it had to leave behind.
 */
export type ExportSummary = { 
/**
 * How many mods reached the destination.
 */
exported: number, 
/**
 * Mods with no archive to copy, named as the library names them.
 */
skipped: Array<string>, 
/**
 * What the export wrote, for a surface that offers to reveal it.
 */
destination: string, };
