// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a mod export, emitted per mod.
 */
export type ExportProgress = { current: number, total: number, currentMod: string, };
