// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of an extract of game chunks to disk.
 *
 * One extract runs over any number of archives, so `current` and `total`
 * count the whole run rather than the archive being read. The extractor
 * reports every chunk it finishes, which is tens of thousands for a large
 * archive, so the emitter throttles rather than sending one of these each
 * time.
 */
export type ExtractProgress = { current: number, total: number, 
/**
 * The chunk just written, or its hex hash when nothing names it.
 */
currentPath: string | null, 
/**
 * Bytes written so far across the whole run.
 */
bytes: bigint, 
/**
 * The `DATA/FINAL`-relative archive being read.
 */
archive: string, };
