// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExistingFiles } from "./ExistingFiles";
import type { ExtractLayout } from "./ExtractLayout";
import type { WorkshopFileKind } from "./WorkshopFileKind";

/**
 * Everything one extract needs beyond the targets themselves.
 */
export type ExtractOptions = { 
/**
 * The folder to write into. Made if it is not there.
 */
destination: string, layout: ExtractLayout, 
/**
 * Put each archive's files under a folder of the archive's own name,
 * which is the layout a layer holds.
 */
perArchiveFolder: boolean, existing: ExistingFiles, 
/**
 * The browser's filter chips. `None` writes every kind.
 */
kinds: Array<WorkshopFileKind> | null, };
