// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an extract will write, before it writes anything.
 *
 * The dialog's summary line reads this, so a user sees the count, the size
 * and the archives before choosing a destination.
 */
export type ExtractPlan = { files: number, 
/**
 * Uncompressed bytes, which is what lands on disk.
 */
bytes: bigint, 
/**
 * The `DATA/FINAL`-relative archives the run reads, in the order it does.
 */
archives: Array<string>, };
