// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the browser, as a thing to extract.
 */
export type ExtractTarget = { "kind": "file", wad: string, pathHash: string, path: string | null, sizeBytes: number, } | { "kind": "dir", path: string, } | { "kind": "archive", wad: string, };
