// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where each file of an extract lands under the destination.
 */
export type ExtractLayout = "paths" | "flat";
