// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkshopFileKind } from "./WorkshopFileKind";

/**
 * One kind of file an extract wrote, and how many.
 */
export type ExtractKindCount = { kind: WorkshopFileKind, count: number, };
