// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mod the migration could not convert.
 */
export type FailedConversion = { 
/**
 * The mod's index id, which is also the directory the uuid layout gave it.
 */
id: string, 
/**
 * What to call the mod in the failure list, falling back to its id.
 */
displayName: string, 
/**
 * Why it could not be moved, in the words the user reads.
 */
error: string, 
/**
 * Where the mod's original files were parked.
 */
quarantineDir: string, };
