// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FantomeImportStage } from "./FantomeImportStage";

/**
 * Progress of a fantome import.
 */
export type FantomeImportProgress = { stage: FantomeImportStage, 
/**
 * The unit being unpacked, as the archive names it: a WAD, or `RAW` for
 * the pass that unpacks everything the archive keeps outside one.
 */
currentItem: string | null, current: number, total: number, };
