// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stage of a fantome import.
 */
export type FantomeImportStage = "extracting" | "finalizing" | "complete" | "error";
