// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KindShape } from "./KindShape";

/**
 * One field's type over one span of builds.
 */
export type FieldRevision = { 
/**
 * The first content build the revision holds for.
 */
from: number, 
/**
 * The last content build it holds for, inclusive. Open where absent.
 */
to: number | null, 
/**
 * Absent for a type this build cannot map.
 */
shape: KindShape | null, };
