// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldRevision } from "./FieldRevision";
import type { KindShape } from "./KindShape";

/**
 * One field of a class: its name, its type at the card's build, and every revision.
 */
export type FieldSchema = { 
/**
 * `0x` and eight hex digits.
 */
hash: string, 
/**
 * The field as the database names it.
 */
name: string | null, 
/**
 * The type at the card's build. Absent where no revision covers the build, and
 * where the revision names a type this build cannot map.
 */
declared: KindShape | null, 
/**
 * Oldest first.
 */
revisions: Array<FieldRevision>, };
