// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one fix run did to one file.
 */
export type FileOutcome = { layer: string, 
/**
 * POSIX-style and relative to the layer root.
 */
path: string, applied: number, skipped: number, };
