// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a repair would change, in the words a row draws.
 *
 * The type it moves the property to is [`Problem::mismatch`] rather than a
 * field here, because a problem no rule can repair still has one to draw.
 */
export type FixPreview = { 
/**
 * What the values alone do not say, such as `3 items`.
 */
note?: string, 
/**
 * The value now, rendered. `None` where a container draws its count instead.
 */
before: string | null, 
/**
 * The value after, rendered. `None` for the same reason as `before`.
 */
after: string | null, };
