// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One restore point a project holds.
 */
export type FixRunSummary = { stamp: string, at: string, 
/**
 * The manager version that wrote it.
 */
manager: string, 
/**
 * The migration tables the run applied.
 */
tables: Array<string>, files: number, applied: number, };
