// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file the full search matched, shaped as an entry a file tree can hold.
 *
 * The pattern is matched over the full path, and the marked runs arrive
 * split at the basename: `name_ranges` are byte offsets into `name`, and
 * `path_ranges` are byte offsets into the directory prefix of `path`.
 */
export type GameFindHit = { 
/**
 * Chunk path hash as 16 lowercase hex digits.
 */
pathHash: string, 
/**
 * Resolved path with forward slashes, or `None` when no hash table names the chunk.
 */
path: string | null, 
/**
 * The path's basename, or the hash when no hash table names the chunk.
 */
name: string, 
/**
 * The `DATA/FINAL`-relative archive the chunk was read from.
 */
wad: string, 
/**
 * Uncompressed chunk size.
 */
sizeBytes: bigint, nameRanges: Array<[number, number]>, pathRanges: Array<[number, number]>, };
