// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameFindHit } from "./GameFindHit";

/**
 * What one full search of the folded index found.
 */
export type GameFindResult = { 
/**
 * Every matching row in tree order, capped at [`FIND_LIMIT`].
 */
hits: Array<GameFindHit>, 
/**
 * How many files matched in all, counted on past the cap.
 */
total: number, 
/**
 * A newer search started before this one finished, so it gave up early.
 *
 * Its rows are whatever it had found, which is not the whole answer. The
 * caller is expected to be showing the newer pattern by now.
 */
superseded: boolean, 
/**
 * No hash table named a single chunk, so only a hash can match.
 */
unnamed: boolean, };
