// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row a search matched, with the runs its two lines mark.
 *
 * Marked runs are byte offsets into `name` and `path`, which the palette
 * slices to lift the matched characters out of the rest.
 */
export type GameSearchHit = { 
/**
 * Chunk path hash as 16 lowercase hex digits.
 */
pathHash: string, 
/**
 * The path's basename, or the hash when no hash table names the chunk.
 */
name: string, 
/**
 * The directory holding it, empty at the root and for an unnamed chunk.
 */
path: string, 
/**
 * The `DATA/FINAL`-relative archive the chunk was read from.
 */
wad: string, 
/**
 * 0 is a name the query opens, 1 a name holding it, 2 a match reaching the directory.
 */
band: number, score: number, nameRanges: Array<[number, number]>, pathRanges: Array<[number, number]>, };
