// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSearchHit } from "./GameSearchHit";

/**
 * What one search of the folded index found.
 */
export type GameSearchResult = { 
/**
 * The best rows, best first, capped at [`SEARCH_LIMIT`].
 */
hits: Array<GameSearchHit>, 
/**
 * How many files matched in all, which the cap trimmed.
 */
total: number, 
/**
 * A newer search started before this one finished, so it gave up early.
 *
 * Its rows are whatever it had found, which is not the whole answer. The
 * caller is expected to be showing the newer query by now.
 */
superseded: boolean, 
/**
 * No hash table named a single chunk, so only a hash can match.
 *
 * An install whose names never resolved answers every path query with
 * nothing, which reads exactly like an install that holds no match. The
 * caller says which of the two it is.
 */
unnamed: boolean, };
