// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way a read of GitHub failed, as the remedy it has.
 */
export type GitHubErrorKind = "OFFLINE" | "RATE_LIMITED" | "HTTP";
