// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the things GitHub publishes a read was after.
 */
export type GitHubFeed = "RELEASES" | "ANNOUNCEMENTS" | "NOTICES";
