// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stage of a git repository import.
 */
export type GitImportStage = "downloading" | "extracting" | "complete" | "error";
