// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipEvent } from "./ClipEvent";
import type { KeyRef } from "./KeyRef";
import type { NamedAsset } from "./NamedAsset";

/**
 * One entry of `mClipDataMap`, of any kind of `ClipBaseData`.
 */
export type GraphClip = { 
/**
 * The clip's key as the tables name it, and its hash where none does.
 */
name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The clip's class as the tables name it, and its hash where none does.
 */
class: string, 
/**
 * `mAnimationResourceData.mAnimationFilePath`, which an atomic clip alone names.
 */
animation: NamedAsset | null, 
/**
 * `mTrackDataName`.
 */
track: KeyRef | null, 
/**
 * `mMaskDataName`.
 */
mask: KeyRef | null, 
/**
 * `mSyncGroupDataName`.
 */
syncGroup: KeyRef | null, 
/**
 * `mTickDuration`, seconds per tick, which an atomic clip alone sets.
 */
tickDuration: number | null, 
/**
 * `mEventDataMap`, in map order.
 */
events: Array<ClipEvent>, 
/**
 * The clips this one plays, in its kind's field order.
 */
children: Array<KeyRef>, 
/**
 * `mValue` of each pair of a parametric clip, one per child in the same order, and
 * empty for every other kind.
 */
parameters: Array<number>, 
/**
 * `mAnimationInterruptionGroupNames`.
 */
interruptionGroups: Array<string>, 
/**
 * `mFlags`.
 */
flags: number, };
