// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What preserving a mod's names at import found.
 *
 * Recorded on the entry rather than only logged: `unharvestable` is what
 * tells a mod that preserved cleanly from one that arrived already lossy,
 * and that distinction should outlive a log rotation.
 */
export type HarvestSummary = { 
/**
 * Names the archive gained on the way in. Zero means every recoverable
 * name was already declared or covered by the community tables.
 */
namesAdded: number, 
/**
 * Chunks with no recoverable name: hex-named, and named by nothing the
 * harvest could read.
 */
unharvestable: number, };
