// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a completed sync run changed.
 */
export type HashtableSyncReport = { 
/**
 * True when nothing needed installing.
 */
upToDate: boolean, 
/**
 * Ids of the tables installed by this run.
 */
installed: Array<string>, 
/**
 * Remote table ids this build does not know. Skipped, never fatal.
 */
unknownTables: Array<string>, 
/**
 * Ids published in a `.hashdb` format this build cannot open. Skipped, so
 * the cache keeps serving what it already holds and only a newer app can
 * install these.
 */
unsupportedTables: Array<string>, };
