// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hash a bin names something outside the graph by, such as a submesh or a joint.
 *
 * The tables name a few of them. A viewport matches the hash against the names the `.skn`
 * or the `.skl` spells, which is how the engine reaches them too.
 */
export type HashRef = { 
/**
 * The hash as the tables name it, and its hex where none does.
 */
name: string, 
/**
 * The hash, `0x` and eight hex digits.
 */
hash: string, };
