// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One table the published release has a version of that this cache does not.
 */
export type HashtableUpdate = { 
/**
 * Stable table id, e.g. `game`.
 */
id: string, 
/**
 * The version the cache holds, absent when it holds none.
 */
have: string | null, 
/**
 * The version the release publishes.
 */
want: string, };
