// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a hashtable sync, as its tables stream in.
 *
 * Every figure describes the whole run rather than the table in flight, so a
 * reader draws one bar for the sync instead of one that restarts per file.
 * The tables are tens of megabytes each, so the emitter throttles rather than
 * sending one of these per chunk.
 */
export type HashtableSyncProgress = { 
/**
 * Id of the table being fetched, e.g. `game`.
 */
table: string, 
/**
 * Which table of the run this is, counting from 1.
 */
current: number, 
/**
 * How many tables the run fetches.
 */
total: number, 
/**
 * Bytes of the whole run written so far.
 */
downloaded: bigint, 
/**
 * Bytes the whole run will write, absent against a release that recorded
 * no sizes.
 */
totalBytes: bigint | null, };
