// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One present table in a [`HashtableCacheStatus`].
 */
export type HashtableStatus = { 
/**
 * Stable table id, e.g. `game`.
 */
id: string, 
/**
 * Active `.lhdb` filename from the manifest.
 */
file: string, 
/**
 * The release this table was published in, e.g. `2026-07-10`.
 *
 * Per table rather than per cache: a sync only installs what changed, so
 * two tables in one cache can be of different vintages.
 */
version: string, 
/**
 * Entry count recorded in the manifest.
 */
entries: bigint, 
/**
 * On-disk size of the active file, or 0 when it cannot be read.
 */
sizeBytes: bigint, 
/**
 * Repository this table's inputs came from, e.g. `CommunityDragon/Data`.
 */
sourceRepo: string | null, 
/**
 * Commit of that repository the inputs were taken at.
 */
sourceCommit: string | null, };
