// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a check can run, and what it is waiting on when it cannot.
 *
 * The precondition in [`hashtables_ready`](ModLibrary::hashtables_ready) as a
 * control can be drawn from: a command a user may press now, one the app is
 * already working towards, and one only they can clear. Per "The hashtables
 * come first" in docs/ux/MOD_HEALTH.md.
 */
export type HealthCheckReadiness = "ready" | "syncing" | "unsynced";
