// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A [`BinHash`] written as `0x` and eight hex digits, which is how a user reads one.
 */
export type HexBinHash = string;
