// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which stage of a start failed, for [`PatcherError::InjectionFailed`].
 */
export type InjectionStage = "HOST" | "INJECTION";
