// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModArchiveFormat } from "./ModArchiveFormat";
import type { ModFault } from "./ModFault";
import type { ModLayer } from "./ModLayer";
import type { ModStorage } from "./ModStorage";

/**
 * A mod entry shown in the UI Library.
 */
export type InstalledMod = { id: string, name: string, displayName: string, version: string, description: string | null, authors: Array<string>, enabled: boolean, installedAt: string, layers: Array<ModLayer>, tags: Array<string>, champions: Array<string>, maps: Array<string>, 
/**
 * Directory where the mod is installed
 */
modDir: string, 
/**
 * The file this mod arrived as.
 */
format: ModArchiveFormat, 
/**
 * Where this mod's content is read from.
 */
storage: ModStorage, 
/**
 * Whether the archive is still beside the mod, which is what makes
 * [`storage`](Self::storage) switchable either way.
 */
hasArchive: boolean, 
/**
 * ID of the containing folder, or None if ungrouped.
 */
folderId: string | null, 
/**
 * Set when the mod is in the library but unusable. The card shows the
 * reason and refuses to enable it.
 */
fault?: ModFault | null, };
