// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The install the manager is set up for, against the one the client's League
 * session runs from.
 */
export type InstallMismatch = { 
/**
 * The install root the manager is set up for.
 */
configuredPath: string, 
/**
 * The patchline the registry lists that root under.
 */
configuredPatchline: string, 
/**
 * The patchline of the League session the client has open.
 */
sessionPatchline: string, 
/**
 * That patchline's install root.
 */
sessionPath: string, };
