// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a bulk mod install, emitted per file.
 */
export type InstallProgress = { current: number, total: number, currentFile: string, };
