// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A retryable integration failure.
 */
export type IntegrationError = { "kind": "unsupported" } | { "kind": "busy" } | { "kind": "conflict" } | { "kind": "notInstalled" } | { "kind": "invalidReceipt" } | { "kind": "release", detail: string, } | { "kind": "integrity" } | { "kind": "cancelled" } | { "kind": "operation", detail: string, };
