// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key one clip names into a map of the graph.
 */
export type KeyRef = { 
/**
 * The key as the tables name it, and its hash where none does.
 */
name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The map holds an entry under the key.
 */
declared: boolean, };
