// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyKind } from "./PropertyKind";

/**
 * A type as the tag composes it: the kind, a `Map`'s key, and what a container holds.
 *
 * The wire form of [`Shape`]. A row's tag and a card's field draw it as `list[embed]`
 * or `map[hash,string]`.
 */
export type KindShape = { kind: PropertyKind, 
/**
 * A `Map`'s key kind.
 */
key: PropertyKind | null, 
/**
 * What an `Option`, a list or a `Map` holds.
 */
value: PropertyKind | null, };
