// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the library's primary button is.
 *
 * `Classic` is the behaviour from before the manager could launch anything:
 * the button only starts the patcher, and the game is started wherever the
 * user started it before. `Modern` makes it the whole path in one click -
 * build the overlay, start the patcher, then ask the Riot Client to start
 * League. Both actions stay reachable from the button's menu either way.
 *
 * Classic is the default while the launcher is experimental: it is the
 * behaviour every existing install already has, and it depends on nothing
 * outside this app.
 */
export type LaunchMode = "classic" | "modern";
