// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stage of a League launch request.
 *
 * A launch is a single blocking call that can spend a minute inside one step -
 * waking a tray-idle client and waiting for it to load its launcher plugin.
 * Without these the caller cannot tell that wait apart from a hang, which is
 * the whole reason they exist.
 */
export type LaunchStage = "resolving" | "handingOff" | "coldStart" | "wakingClient" | "waitingForClient" | "launched" | "alreadyRunning" | "error";
