// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stage of a League launch request.
 *
 * A launch is one blocking call that can spend a minute inside a single step,
 * waking a tray-idle client. Without these the frontend cannot tell that wait
 * apart from a hang.
 */
export type LaunchStage = "resolving" | "handingOff" | "coldStart" | "wakingClient" | "waitingForClient" | "launched" | "alreadyRunning" | "stopped" | "error" | "unknown";
