// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchRoute } from "./LaunchRoute";

/**
 * The result of a successful launch request.
 *
 * "Successful" means the Riot Client took the request, not that the game is up:
 * the client may still be updating itself, or waiting for the user to log in.
 */
export type LaunchOutcome = { route: LaunchRoute, 
/**
 * Pid of the Riot Client - the one we spawned on a cold start, the one
 * from the lockfile otherwise.
 */
riotClientPid: number | null, 
/**
 * The session id the client minted, when it told us one. This is the key
 * into `/product-session/v1/external-sessions`, so it is what a future
 * "did the game actually start?" check should follow rather than scanning
 * for a process name.
 */
sessionId: string | null, };
