// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a launch request could not be delivered.
 *
 * Each variant has a different remedy ("set your game path", "open the Riot
 * Client"), so each gets its own `ErrorCode` in the shell rather than sharing
 * one with a discriminating field.
 */
export type LauncherError = { "kind": "RIOT_CLIENT_NOT_FOUND", installsPath: string, } | { "kind": "RIOT_CLIENT_UNREACHABLE", reason: string, } | { "kind": "REFUSED", riotErrorCode: string, message: string, } | { "kind": "STOPPED" } | { "kind": "MISCONFIGURED", reason: string, } | { "kind": "SPAWN_FAILED", reason: string, } | { "kind": "UNSUPPORTED_PLATFORM" } | { "kind": "OTHER", message: string, };
