// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchStage } from "./LaunchStage";

/**
 * Progress of a League launch request.
 */
export type LaunchProgress = { stage: LaunchStage, 
/**
 * Seconds spent waiting for the client so far. Only meaningful during
 * [`LaunchStage::WaitingForClient`], zero everywhere else.
 */
waitedSecs: number, 
/**
 * How long that wait may run before it gives up. Zero outside the wait.
 */
timeoutSecs: number, };
