// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a launch is possible right now, and why not if it isn't.
 *
 * Drives the button's disabled state, so it never fails: an unanswerable
 * question resolves to "can't launch" rather than an error the UI has to
 * render.
 */
export type LaunchAvailability = { 
/**
 * Whether the platform supports launching and a Riot Client was resolved.
 */
canLaunch: boolean, 
/**
 * The resolved `RiotClientServices.exe`, when one was found.
 */
riotClientPath: string | null, 
/**
 * Whether a Riot Client is alive, i.e. whether a launch would take the
 * handoff route rather than cold-starting.
 */
riotClientRunning: boolean, 
/**
 * Whether `LeagueClient.exe` is already up.
 */
leagueRunning: boolean, };
