// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a launch request could not be delivered.
 *
 * These deliberately do not share one code: each variant has a different
 * remedy ("set your League path", "open the Riot Client"), so a host can map
 * each to its own error code and branch on that.
 *
 * Read-only queries do not use this type - they answer `Option`, because the
 * caller always has a fallback and "the client didn't tell us" is not a failure
 * worth surfacing.
 */
export type LauncherError = { "kind": "RIOT_CLIENT_NOT_FOUND", installsPath: string, } | { "kind": "RIOT_CLIENT_UNREACHABLE", reason: string, } | { "kind": "LAUNCH_REFUSED", riotErrorCode: string, message: string, } | { "kind": "SPAWN_FAILED", reason: string, } | { "kind": "UNSUPPORTED_PLATFORM" };
