// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the launch request was delivered.
 */
export type LaunchRoute = "EXISTING_CLIENT" | "COLD_START" | "ALREADY_RUNNING";
