// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which product and patchline to launch.
 *
 * These are data, not an enum to invent: `league_of_legends` / `live` is what
 * the client's own product registry uses, `pbe` exists as a patchline, and
 * anything else should come from configuration rather than a guess.
 */
export type LaunchTarget = { productId: string, patchlineId: string, };
