// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of one project layer, as [`AssetRef::Layer`](crate::preview::AssetRef::Layer) names it.
 */
export type LayerFile = { 
/**
 * The layer's directory name under `content`.
 */
layer: string, 
/**
 * Path relative to the layer root, with forward slashes.
 */
path: string, };
