// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredMark } from "./DeclaredMark";

/**
 * One row of a layer file that a declaration of the project overrides. ADR-0056.
 */
export type LayerOverride = { 
/**
 * The layer whose `game_data.yaml` holds the declaration.
 */
layer: string, 
/**
 * The declaration's mark. Its `game` field holds the file's value, not the game's.
 */
mark: DeclaredMark, 
/**
 * The value the declaration writes, as YAML. Absent when it cannot be written as YAML.
 */
value: string | null, };
