// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerFile } from "./LayerFile";

/**
 * Layer files of one workshop project that changed on disk.
 */
export type LayerFilesChanged = { 
/**
 * The project directory, spelled as the watch on it was asked for.
 */
project: string, 
/**
 * Each file once, in order.
 */
files: Array<LayerFile>, };
