// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutMigrationReport } from "./LayoutMigrationReport";

/**
 * What the layout migration has to say for itself this launch.
 *
 * The run starts with the app, so a window that opens afterwards has no
 * [`LayoutMigrationFinished`](crate::events::BackendEvent) event to catch. It
 * asks instead, and [`Pending`](Self::Pending) is what tells it to ask again.
 */
export type LayoutMigrationState = { "status": "pending" } | { "status": "idle" } | { "status": "finished", report: LayoutMigrationReport, };
