// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of the library layout migration, emitted per mod.
 *
 * Separate from [`MigrationProgress`], which is the cslol import: the two run
 * at different moments, mean different things, and share nothing but the word.
 */
export type LayoutMigrationProgress = { current: number, total: number, currentMod: string, };
