// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedConversion } from "./FailedConversion";

/**
 * What one migration run did.
 */
export type LayoutMigrationReport = { 
/**
 * How many mods reached the slug layout.
 */
migrated: number, 
/**
 * The mods that did not, each naming where its files went instead.
 */
failed: Array<FailedConversion>, };
