// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The value a leaf edit sets, in the shape its widget holds.
 *
 * A hash, a link and a file carry the text the reader typed: a name, or the hex the row
 * draws.
 */
export type LeafValue = { "type": "bool", value: boolean, } | { "type": "integer", text: string, } | { "type": "float", value: number, } | { "type": "vector", values: Array<number>, } | { "type": "matrix", values: Array<number>, } | { "type": "color", r: number, g: number, b: number, a: number, } | { "type": "string", value: string, } | { "type": "hash", text: string, } | { "type": "wadChunkLink", text: string, } | { "type": "objectLink", text: string, };
