// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One character a map stands in its scene.
 */
export type MapCharacter = { 
/**
 * The placeable's own name, which is unique within a map.
 */
name: string, 
/**
 * The entry path of the skin it wears, such as `Characters/Turret/Skins/Skin0`.
 */
skin: string, 
/**
 * Where it stands in the map's space, column major with the translation last.
 */
transform: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * The layer mask, one bit per visibility layer, as a map mesh carries one.
 */
visibility: number, 
/**
 * The controller that shows and hides it, which no layer mask expresses.
 */
controller: string | null, 
/**
 * The team it stands for, where it states one. 300 is the neutral team a camp is on.
 */
team: number | null, 
/**
 * The clip a `GDSMapObjectAnimationInfo` names for it, by the name its graph keys it
 * under. None plays whatever the graph idles on.
 */
animation: string | null, };
