// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapItemKind } from "./MapItemKind";

/**
 * One placeable of a chunk.
 */
export type MapChunkItem = { 
/**
 * The key it sits under in its chunk, as `0x` and eight digits.
 */
key: string, 
/**
 * The placeable's own name, and the hash itself where nothing names one.
 */
name: string, 
/**
 * Its class by name, and by hash where no table names it.
 */
class: string, kind: MapItemKind, 
/**
 * Where it stands in the map's space.
 */
position: [number, number, number], 
/**
 * The layer mask, one bit per visibility layer.
 */
visibility: number, 
/**
 * The controller that shows and hides it, which no layer mask expresses.
 */
controller: string | null, };
