// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapChunkItem } from "./MapChunkItem";

/**
 * One chunk of a map and everything it holds, in file order.
 */
export type MapChunk = { 
/**
 * The `MapPlaceableContainer` object, as `0x` and eight digits.
 */
entry: string, 
/**
 * The object's path, else the key a `MapContainer` lists it under, else none.
 */
name: string | null, items: Array<MapChunkItem>, };
