// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The depth of field of [`MapPostEffects`].
 */
export type MapDepthOfField = { 
/**
 * The blur is drawn.
 */
enabled: boolean, 
/**
 * The distance from the camera that is sharpest.
 */
focalDistance: number, 
/**
 * How deep the sharp band around `focal_distance` is.
 */
inFocusWidth: number, 
/**
 * `Coc`, the circle of confusion the blur widens to.
 */
coc: number, };
