// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";

/**
 * Where the two files of one map live, each none where nothing holds it.
 */
export type MapFiles = { 
/**
 * The `.mapgeo`, which the scheme answers as one buffer.
 */
geometry: AssetRef | null, 
/**
 * The `.materials.bin`, which declares the materials and the chunks.
 */
materials: AssetRef | null, };
