// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One fog of [`MapPostEffects`], ramping from nothing at `start` to its most at `end`.
 */
export type MapFog = { 
/**
 * The fog is drawn.
 */
enabled: boolean, 
/**
 * RGBA with each channel 0 to 1, as the bin writes it.
 */
color: [number, number, number, number], 
/**
 * Where the fog begins, a distance or a height in world units.
 */
start: number, 
/**
 * Where the fog reaches `max_intensity`.
 */
end: number, 
/**
 * The most the fog covers, 0 to 1.
 */
maxIntensity: number, };
