// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a placeable is to a scene, which is what an outliner marks its row with.
 */
export type MapItemKind = "particle" | "character" | "locator" | "group" | "audio" | "other";
