// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialPreview } from "./MaterialPreview";

/**
 * One map's materials, one per path asked for and in that order.
 */
export type MapModel = { 
/**
 * Null where the map's own bin declares no object at that path, which a backdrop
 * draws flat rather than not at all.
 */
materials: Array<MaterialPreview | null>, };
