// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a map lives, as `MapContainer.mapPath` states it.
 *
 * An entry path rather than a file path, such as `Maps/MapGeometry/Map11/Base_SRX`. It
 * names no file of its own: each of a map's files is this path lowercased under the
 * data prefix with that file's suffix, which is the one spelling a resolved WAD path
 * has.
 */
export type MapPath = string;
