// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One particle system a map stands in its scene.
 */
export type MapParticle = { 
/**
 * The placeable's own name, which is unique within a map.
 */
name: string, 
/**
 * The system it plays, an object of the same document, as `0x` and eight digits.
 */
system: string, 
/**
 * Where it stands in the map's space, column major with the translation last.
 */
transform: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * The layer mask, one bit per visibility layer, as a map mesh carries one.
 */
visibility: number, 
/**
 * The controller that shows and hides it, which no layer mask expresses.
 */
controller: string | null, 
/**
 * The game plays it once as the map changes rather than for as long as it stands.
 */
transitional: boolean, 
/**
 * The game leaves it off until a script turns it on.
 */
startDisabled: boolean, };
