// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapDepthOfField } from "./MapDepthOfField";
import type { MapFog } from "./MapFog";

/**
 * A map's post effects, as its `PostEffectOptions` states them.
 *
 * A field the map leaves out reads as the class default, which [`MapPostEffects::default`]
 * returns and which switches every effect off.
 */
export type MapPostEffects = { 
/**
 * `DepthFog` and its fields, which fog by distance from the camera.
 */
depthFog: MapFog, 
/**
 * `HeightFog` and its fields, which fog by height in the world.
 */
heightFog: MapFog, 
/**
 * `Dof` and its fields.
 */
depthOfField: MapDepthOfField, };
