// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map's sun, sky and fog, as its `MapSunProperties` states them.
 *
 * Colours are RGBA with each channel 0 to 1, as the bin writes them. A field the map
 * leaves out reads as the class default, which [`MapSun::default`] returns.
 */
export type MapSun = { 
/**
 * `sunDirection`, which points at the sun in the engine's space.
 */
direction: [number, number, number], 
/**
 * `sunColor`.
 */
color: [number, number, number, number], 
/**
 * `SunIntensityScale`.
 */
intensity: number, 
/**
 * `skyLightColor`, what lights a surface facing up.
 */
skyColor: [number, number, number, number], 
/**
 * `groundColor`, what lights a surface facing down.
 */
groundColor: [number, number, number, number], 
/**
 * `horizonColor`, what lights a surface facing sideways.
 */
horizonColor: [number, number, number, number], 
/**
 * `skyLightScale`.
 */
skyScale: number, 
/**
 * `lightMapColorScale`, which scales a baked light map.
 */
lightMapColorScale: number, 
/**
 * `fogEnabled`.
 */
fogEnabled: boolean, 
/**
 * `fogColor`.
 */
fogColor: [number, number, number, number], 
/**
 * `fogAlternateColor`.
 */
fogAlternateColor: [number, number, number, number], 
/**
 * `fogStartAndEnd`, the heights the fog runs between, the start above the end.
 */
fogStartEnd: [number, number], 
/**
 * `fogEmissiveRemap`.
 */
fogEmissiveRemap: number, };
