// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map's sun and sky, as its `MapSunProperties` states them.
 *
 * Colours are RGBA with each channel 0 to 1, as the bin writes them. A field the map
 * leaves out reads as the class default, which [`MapSun::default`] returns.
 */
export type MapSun = { 
/**
 * `sunDirection`, which points at the sun in the engine's space.
 */
direction: [number, number, number], 
/**
 * `sunColor`.
 */
color: [number, number, number, number], 
/**
 * `SunIntensityScale`.
 */
intensity: number, 
/**
 * `skyLightColor`.
 */
skyColor: [number, number, number, number], 
/**
 * `groundColor`.
 */
groundColor: [number, number, number, number], 
/**
 * `skyLightScale`.
 */
skyScale: number, };
