// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map's screen-space ambient occlusion, as its `MapSSAOSettings` states it.
 *
 * A field the map leaves out reads as the class default, which [`MapSsao::default`]
 * returns.
 */
export type MapSsao = { 
/**
 * `SampleQuality`, 0 for four samples a pixel and 1 for eight.
 */
sampleQuality: number, 
/**
 * `SampleRadius`, how far from a pixel its samples reach, in world units.
 */
sampleRadius: number, 
/**
 * `Bias`, how far in front of a sample the scene must be to occlude it, in world units.
 */
bias: number, 
/**
 * `power`, the exponent the unoccluded share of a pixel is raised to.
 */
power: number, 
/**
 * `intensity`, how much of the occlusion reaches the frame, 0 to 1.
 */
intensity: number, 
/**
 * `BufferScale`, the occlusion's resolution as a share of the frame's.
 */
bufferScale: number, 
/**
 * `EdgeAwareBlur`, the blur keeps a nearer surface's occlusion off the one behind it.
 */
edgeAwareBlur: boolean, };
