// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapPath } from "./MapPath";

/**
 * One map an object draws, and the skin that names it.
 */
export type MapVariant = { 
/**
 * The `MapSkin`'s own name, and none for a map a container states itself.
 */
skin: string | null, 
/**
 * The map that skin draws.
 */
map: MapPath, 
/**
 * The file that map declares its materials and its chunks in.
 */
materials: string, };
