// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of `mMaskDataMap`.
 */
export type Mask = { name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * `mId`.
 */
id: number, 
/**
 * `mWeightList`, one weight per joint of the skeleton in the skeleton's order.
 */
weights: Array<number>, };
