// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialKind } from "./MaterialKind";
import type { MaterialWarning } from "./MaterialWarning";
import type { PassProgram } from "./PassProgram";

/**
 * One material with a program per pass, as the viewport binds it.
 */
export type MaterialProgram = { 
/**
 * The material's path hash, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The material's path, where a table names it.
 */
name: string | null, 
/**
 * `dynamicMaterial` is set, so the passes hold the static values of an animated
 * material.
 */
animated: boolean, kind: MaterialKind, 
/**
 * The passes of the `normal` technique, in draw order.
 */
passes: Array<PassProgram>, 
/**
 * Every drop, miss and fallback the read made, in the order it made them.
 */
warnings: Array<MaterialWarning>, };
