// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which typed view writes a member.
 */
export type MemberScalar = "float" | "int" | "uint" | "bool";
