// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The movement class and its written speed or duration.
 */
export type MissileMovement = { "kind": "fixedSpeed", speed: number | null, } | { "kind": "fixedTime", duration: number | null, } | { "kind": "unsupported", class_hash: string, } | { "kind": "missing" };
