// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissileMovement } from "./MissileMovement";

/**
 * A missile's written placement inputs, with omitted values kept absent.
 */
export type MissileSpec = { 
/**
 * The movement component.
 */
movement: MissileMovement, 
/**
 * The written launch delay, without the spell's cast timing added.
 */
startDelay: number | null, 
/**
 * The requested launch bone, which an isolated preview replaces with a point.
 */
startBone: string | null, 
/**
 * The requested target bone, which an isolated preview replaces with a point.
 */
targetBone: string | null, 
/**
 * The target's height adjustment.
 */
targetHeight: number | null, 
/**
 * The initial target-height offset.
 */
initialTargetHeight: number | null, };
