// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The file a mod arrived as. Provenance only — [`ModStorage`] is what decides
 * how it is read.
 */
export type ModArchiveFormat = "modpkg" | "fantome" | "unknown";
