// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a mod is in the library but unusable.
 *
 * One variant today. The shape is the seam autofix grows into: a scanned
 * import that needs repair is the same idea — an entry the user can still see,
 * excluded from overlay builds until something resolves it.
 */
export type ModFault = { "kind": "conversionFailed", error: string, quarantineDir: string, };
