// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The one word a mod's badge says.
 */
export type ModHealth = "healthy" | "repairable" | "unrepairable";
