// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a mod's content is, which is what picks its content provider.
 *
 * Recorded rather than derived: a fantome installs as
 * [`Archive`](Self::Archive) but the user can unpack it after the fact, and a
 * future sanitized-fantome mode would be another value here rather than
 * another guess from the layout.
 */
export type ModStorage = "project" | "archive";
