// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FantomeImportStage } from "./FantomeImportStage";
import type { ModStorage } from "./ModStorage";

/**
 * Progress of one mod moving between the two storage modes.
 *
 * Its own event though an unpack is a fantome import, because the workshop's
 * import dialog listens on `fantome-import-progress` and a library conversion
 * must not drive it. The stage is shared, since the two report the same four
 * states.
 */
export type ModStorageProgress = { modId: string, 
/**
 * The storage the mod is moving to, which is what names the work.
 */
storage: ModStorage, stage: FantomeImportStage, 
/**
 * As [`FantomeImportProgress::current_item`].
 */
currentItem: string | null, current: number, total: number, };
