// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An item Add item writes into a list, a map or an option.
 */
export type NewItem = { 
/**
 * Where the item lands in a list or a map, or `None` for the end.
 */
index: number | null, 
/**
 * A map entry's key as a person types one: digits, the text of a `string`, or a name
 * or `0x` and eight hex digits for a `hash`.
 */
key: string | null, 
/**
 * The class an embed or a pointer item holds, as a name or `0x` and eight hex digits.
 * A pointer item without one starts null.
 */
class: string | null, };
