// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KindShape } from "./KindShape";

/**
 * A property Add property writes: a field the schema declares, or one the reader shapes.
 */
export type NewProperty = { "kind": "declared", 
/**
 * `0x` and eight hex digits.
 */
field: string, } | { "kind": "custom", 
/**
 * A field name, or `0x` and eight hex digits.
 */
field: string, shape: KindShape, 
/**
 * The class an embed holds, as a name or `0x` and eight hex digits.
 */
class: string | null, };
