// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node of one bin: which object, and where inside it.
 *
 * This is the game's own property path, which is what a `PTCH` record carries
 * and what Riot's tools address a property with. A path begins inside an
 * object and never names it, which is why the entry hash sits beside it.
 */
export type NodeAddress = { 
/**
 * The object's path hash, which the file addresses it by.
 */
entry: string, 
/**
 * The property path, empty for the object itself.
 *
 * Every segment is a hash, which is what the file itself holds. A repair
 * matches on this, so what the hash tables can or cannot name never
 * changes what a fix reaches.
 */
path: string, 
/**
 * The same path for reading, where a table named anything in it.
 *
 * Absent when no segment could be named, which is when it would read the
 * same as `path`.
 */
label?: string, };
