// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoticeSeverity } from "./NoticeSeverity";

/**
 * One notice that concerns the running build, and has not expired.
 */
export type Notice = { 
/**
 * Stable across edits, which is what a dismissal is kept by.
 */
id: string, severity: NoticeSeverity, title: string, 
/**
 * Where "What to do" opens, when the notice has somewhere to send a reader.
 */
url: string | null, 
/**
 * RFC 3339.
 */
publishedAt: string, };
