// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row a search matched, with the runs its path marks.
 *
 * The object's whole path is the row's title, so `ranges` are byte offsets
 * into `path`. An object or a class no table names reads as its hex.
 */
export type ObjectSearchHit = { 
/**
 * The object's path hash, as `0x` and eight hex digits.
 */
objectHash: string, 
/**
 * The object's path, or its hash when no table names it.
 */
path: string, ranges: Array<[number, number]>, 
/**
 * The class the object declares, or its hash when no table names it.
 */
class: string, 
/**
 * The declaring chunk's path hash as 16 lowercase hex digits.
 */
fileHash: string, 
/**
 * The declaring chunk's path.
 */
file: string, 
/**
 * The `DATA/FINAL`-relative archive the declaring chunk was read from.
 */
wad: string, 
/**
 * 0 is a name the query opens, 1 a name holding it, 2 a match reaching the path.
 */
band: number, score: number, };
