// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ReferenceResult } from "./ReferenceResult";

/**
 * What a reference query found, given the slot the index is in.
 */
export type ObjectReferences = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready" } & ReferenceResult;
