// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * The slot the index is in, as an answer reports it.
 */
export type ObjectIndexStatus = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready" };
