// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectNodeEntry } from "./ObjectNodeEntry";
import type { ObjectPrefixEntry } from "./ObjectPrefixEntry";

/**
 * What one prefix of the object tree holds.
 *
 * "Objects browser" in `docs/ux/PROJECT_EDITOR.md`.
 */
export type ObjectDirListing = { 
/**
 * The prefixes no object bears, in natural name order, the unnamed group last at the root.
 */
prefixes: Array<ObjectPrefixEntry>, 
/**
 * The objects at the prefix, in natural name order.
 */
objects: Array<ObjectNodeEntry>, };
