// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";

/**
 * One declaration of an object: the file that declares it and the class it carries.
 */
export type ObjectDeclaration = { 
/**
 * The declaring file, as an open reads it.
 */
asset: AssetRef, 
/**
 * The declaring file's path, or its hash when no table names it.
 */
file: string, 
/**
 * The class hash, as `0x` and eight hex digits.
 */
classHash: string, 
/**
 * The class's name, or its hash when no table names it.
 */
class: string, };
