// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ObjectSearchResult } from "./ObjectSearchResult";

/**
 * What a search answers, given the slot the index is in.
 */
export type ObjectSearch = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready" } & ObjectSearchResult;
