// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectClassHit } from "./ObjectClassHit";
import type { ObjectSearchHit } from "./ObjectSearchHit";

/**
 * What one search of the object index found.
 */
export type ObjectSearchResult = { 
/**
 * The best rows, best first, capped at [`SEARCH_LIMIT`].
 */
hits: Array<ObjectSearchHit>, 
/**
 * How many rows matched in all, which the cap trimmed.
 */
total: number, 
/**
 * A newer search started before this one finished, so it gave up early.
 */
superseded: boolean, 
/**
 * No table named a single object, so only a hash can match.
 */
unnamed: boolean, 
/**
 * The classes an ambiguous `class:` term matched, in place of rows.
 */
classes: Array<ObjectClassHit>, };
