// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One object by hash, and by path where a table names it.
 */
export type ObjectName = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The object's path. Absent where no table names it.
 */
name: string | null, };
