// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectDeclaration } from "./ObjectDeclaration";

/**
 * One object at a listed prefix, with what sits below it.
 */
export type ObjectNodeEntry = { 
/**
 * The object's path hash, as `0x` and eight hex digits.
 */
objectHash: string, 
/**
 * The object's path, or its hash when no table names it.
 */
path: string, 
/**
 * The last segment of the path, or the hash.
 */
name: string, 
/**
 * Every declaration of the object, in archive order.
 */
declarations: Array<ObjectDeclaration>, 
/**
 * Objects below the node, 0 for a leaf.
 */
count: number, };
