// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectDeclaration } from "./ObjectDeclaration";

/**
 * One object the full search matched, with the runs its path marks.
 */
export type ObjectFindHit = { 
/**
 * The object's path hash, as `0x` and eight hex digits.
 */
objectHash: string, 
/**
 * The object's path, or its hash when no table names it.
 */
path: string, 
/**
 * Byte offsets into `path`. Empty where a class term alone matched.
 */
ranges: Array<[number, number]>, 
/**
 * Every declaration of the object, in archive order.
 */
declarations: Array<ObjectDeclaration>, };
