// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One prefix under a listed one, folded through any run of single-child prefixes.
 *
 * A node an object bears is an [`ObjectNodeEntry`] and not one of these.
 */
export type ObjectPrefixEntry = { 
/**
 * What [`ObjectIndex::object_dir`] takes to open this row: the folded node's path.
 */
path: string, 
/**
 * What the row reads: the folded run of segments joined by `/`.
 */
name: string, 
/**
 * Objects below the prefix.
 */
count: number, };
