// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectFindHit } from "./ObjectFindHit";

/**
 * What one full search of the object index found.
 */
export type ObjectFindResult = { 
/**
 * Every matching object in path order, capped at `FIND_LIMIT`, the unnamed last.
 */
hits: Array<ObjectFindHit>, 
/**
 * How many objects matched in all, counted on past the cap.
 */
total: number, 
/**
 * A newer search overtook this one. The hits are a part of the answer.
 */
superseded: boolean, 
/**
 * No table named a single object. Only a hash can match.
 */
unnamed: boolean, };
