// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The path of one bin object, for the hashes a run's problems sit under.
 *
 * A catalogue rather than a field on [`NodeAddress`], for the reason
 * [`RuleInfo`] is one: a file's problems repeat a handful of objects between
 * them, and an object's path is the same string every time it is named.
 *
 * Only the objects a table could name are listed. An object with no entry here
 * is read as the hex of its hash, which is what the file itself holds.
 */
export type ObjectInfo = { 
/**
 * The object's path hash, matching [`NodeAddress::entry`].
 */
entry: string, 
/**
 * The path the hash is of, such as `Characters/Graves/Skins/Skin0`.
 */
name: string, };
