// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ObjectDirListing } from "./ObjectDirListing";

/**
 * What one prefix of the object tree holds, given the slot the index is in.
 */
export type ObjectDir = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready" } & ObjectDirListing;
