// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ObjectFindResult } from "./ObjectFindResult";

/**
 * What a full search of the objects found, given the slot the index is in.
 */
export type ObjectFind = { "status": "absent" } | { "status": "building" } | { "status": "failed", error: AppError, } | { "status": "ready" } & ObjectFindResult;
