// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One class an ambiguous `class:` term matched, offered as a completion.
 */
export type ObjectClassHit = { 
/**
 * The class hash, as `0x` and eight hex digits.
 */
classHash: string, 
/**
 * The class's name, or its hash when no table names it.
 */
class: string, 
/**
 * How many declarations carry the class.
 */
rows: number, };
