// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way an overlay build failed, as the remedy the frontend picks between.
 *
 * Mirrors the categories of `ltk_overlay::Error`, which is not `Serialize`,
 * so the category rides in `context.category` while the detail stays in the
 * message.
 */
export type OverlayErrorCategory = "GAME_DIR" | "MOD_CONTENT" | "WAD_LIMIT" | "CORRUPT" | "BUG" | "OTHER";
