// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which step of section 11.6 last wrote a parameter.
 */
export type ParamSource = "shaderDefault" | "material" | "pass";
