// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendFactor } from "./BlendFactor";
import type { Winding } from "./Winding";

/**
 * The pass's render state, field by field, with the class defaults filled in.
 */
export type PassState = { blendEnable: boolean, srcColor: BlendFactor, dstColor: BlendFactor, srcAlpha: BlendFactor, dstAlpha: BlendFactor, cullEnable: boolean, windingToCull: Winding, depthEnable: boolean, 
/**
 * `depthCompareFunc` as written, 3 being less or equal, the default.
 */
depthCompareFunc: number, 
/**
 * `writeMask` as written: bits 1, 2, 4 and 8 the colour channels, 16 depth.
 */
writeMask: number, };
