// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgramRead } from "./ProgramRead";
import type { ResolvedPass } from "./ResolvedPass";

/**
 * One pass with its shader, or with why it has none.
 */
export type PassProgram = { pass: ResolvedPass, program: ProgramRead, };
