// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedAsset } from "./NamedAsset";
import type { SamplerState } from "./SamplerState";
import type { TextureSource } from "./TextureSource";

/**
 * One `ShaderTexture` with the path and the sampler the pass binds it with.
 */
export type PassTexture = { 
/**
 * The shader texture's name, which the material's sampler entry is keyed by.
 */
name: string, 
/**
 * The texture, and none where no step names a path, which the engine's fallback
 * texture draws.
 */
texture: NamedAsset | null, source: TextureSource, sampler: SamplerState, };
