// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamSource } from "./ParamSource";

/**
 * One `ShaderPhysicalParameter` after the material's and the pass's values wrote into it.
 */
export type PassParam = { 
/**
 * The physical name, which the `$Globals` member carries.
 */
name: string, value: [number, number, number, number], 
/**
 * The last step that wrote a component.
 */
source: ParamSource, };
