// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatcherPhase } from "./PatcherPhase";

/**
 * Current status of the patcher.
 */
export type PatcherStatus = { 
/**
 * Whether the patcher is currently running.
 */
running: boolean, 
/**
 * Overlay prefix the running session was started with. `null` while idle.
 */
overlayPrefix: string | null, 
/**
 * Current phase of the patcher lifecycle.
 */
phase: PatcherPhase, };
