// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectionStage } from "./InjectionStage";

/**
 * Domain errors specific to the patcher.
 *
 * Sent over IPC as the `context` payload of an `AppError` with code `PATCHER`.
 * Frontend code can switch on `kind` to handle each variant.
 */
export type PatcherError = { "kind": "BUSY" } | { "kind": "ALREADY_RUNNING" } | { "kind": "NOT_RUNNING" } | { "kind": "UNSUPPORTED_PLATFORM" } | { "kind": "INJECTION_FAILED", stage: InjectionStage, message: string, };
