// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A release newer than the running build.
 */
export type PendingUpdate = { 
/**
 * The release on offer.
 */
version: string, 
/**
 * The build that is running.
 */
currentVersion: string, 
/**
 * The release notes, in markdown.
 */
body: string | null, };
