// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much a problem costs the mod.
 */
export type ProblemSeverity = "fatal" | "error" | "warning" | "info";
