// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixPreview } from "./FixPreview";
import type { ProblemId } from "./ProblemId";
import type { ProblemSeverity } from "./ProblemSeverity";
import type { RuleId } from "./RuleId";
import type { Site } from "./Site";
import type { TypeMismatch } from "./TypeMismatch";

/**
 * One finding, at one site, from one rule.
 */
export type Problem = { 
/**
 * Stable within a run, so the panel keys a row by it.
 */
id: ProblemId, rule: RuleId, severity: ProblemSeverity, site: Site, 
/**
 * The types this problem is about, where the rule is about types.
 */
mismatch?: TypeMismatch, 
/**
 * What this one problem needs said beyond [`RuleInfo::description`].
 */
message?: string, 
/**
 * What a repair would change, drawn before it is applied.
 */
fix: FixPreview | null, };
