// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One finding, at one site, from one rule.
 *
 * The id is derived from the rule and the site, so the same problem carries
 * the same id in two runs and a panel's selection survives a re-run.
 */
export type ProblemId = string;
