// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the studio adds to a pass's define list.
 */
export type ProgramOptions = { 
/**
 * `LOW_QUALITY_MODE`, the game's own low setting.
 */
lowQuality: boolean, };
