// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageProgram } from "./StageProgram";

/**
 * A pass's two stages translated, or the reason the viewport draws it as an error.
 */
export type ProgramRead = { "kind": "ready", 
/**
 * The define list the permutation was picked by, `NAME=VALUE` sorted by name,
 * with the studio's own entries added.
 */
defines: Array<string>, vertex: StageProgram, pixel: StageProgram, } | { "kind": "failed", reason: string, };
