// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 27 kinds `ltk_meta` reads, as they cross IPC.
 *
 * A mirror of [`Kind`]. An upstream rename or addition is a compile error here.
 */
export type PropertyKind = "none" | "bool" | "i8" | "u8" | "i16" | "u16" | "i32" | "u32" | "i64" | "u64" | "f32" | "vector2" | "vector3" | "vector4" | "matrix44" | "color" | "string" | "hash" | "wadChunkLink" | "container" | "unorderedContainer" | "struct" | "embedded" | "objectLink" | "optional" | "map" | "bitBool";
