// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 27 kinds `ltk_meta` reads, as they cross IPC.
 *
 * A mirror of [`Kind`], spelled in ritobin's words. The spelling is the tag a row
 * draws and the word a Problems finding writes. An upstream rename or addition is a
 * compile error here.
 */
export type PropertyKind = "none" | "bool" | "i8" | "u8" | "i16" | "u16" | "i32" | "u32" | "i64" | "u64" | "f32" | "vec2" | "vec3" | "vec4" | "mtx44" | "rgba" | "string" | "hash" | "file" | "list" | "list2" | "pointer" | "embed" | "link" | "option" | "map" | "flag";
