// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a reference query asks for.
 */
export type ReferenceQuery = { "kind": "class", 
/**
 * The class hash, `0x` and eight hex digits.
 */
classHash: string, } | { "kind": "embedded", 
/**
 * The class hash, `0x` and eight hex digits.
 */
classHash: string, } | { "kind": "object", 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
objectHash: string, } | { "kind": "file", 
/**
 * The chunk path, as the tables spell it.
 */
path: string, } | { "kind": "chunk", 
/**
 * The chunk's path hash, sixteen hex digits.
 */
pathHash: string, };
