// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceProperty } from "./ReferenceProperty";

/**
 * One object a reference query found, in the file that declares it.
 */
export type ReferenceHit = { 
/**
 * The object's path hash, as `0x` and eight hex digits.
 */
objectHash: string, 
/**
 * The object's path, or its hash when no table names it.
 */
path: string, 
/**
 * The class hash, as `0x` and eight hex digits.
 */
classHash: string, 
/**
 * The class's name, or its hash when no table names it.
 */
class: string, 
/**
 * Where in the object the walk found the reference. Absent for an answer of the index.
 */
property: ReferenceProperty | null, };
