// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { ReferenceHit } from "./ReferenceHit";

/**
 * The objects one file declares, as a reference query groups them.
 */
export type ReferenceGroup = { 
/**
 * The declaring file, as an open reads it.
 */
asset: AssetRef, 
/**
 * The declaring file's path, or its hash when no table names it.
 */
file: string, 
/**
 * The objects in natural path order, the ones no table names last.
 */
objects: Array<ReferenceHit>, };
