// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceGroup } from "./ReferenceGroup";

/**
 * What one reference query found.
 */
export type ReferenceResult = { 
/**
 * The declaring files in archive order, holding [`FIND_LIMIT`] objects in all.
 */
groups: Array<ReferenceGroup>, 
/**
 * How many objects matched in all, counted on past the cap.
 */
total: number, 
/**
 * A newer query overtook this one. The groups are a part of the answer.
 */
superseded: boolean, };
