// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far one walk has read.
 */
export type ReferenceWalkProgress = { 
/**
 * Bins read, or passed over because they would not read.
 */
walked: number, 
/**
 * Bins the walk reads in all: the project's layers and the install's.
 */
total: number, 
/**
 * References found so far, past any cap.
 */
hits: number, };
