// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The row inside an object that holds a reference, in the two forms a row carries.
 */
export type ReferenceProperty = { 
/**
 * The property path on the wire, every field a hash (ADR-0027).
 */
path: string, 
/**
 * The same path for a person, every hash a table names spelled.
 */
label: string, };
