// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendFactor } from "./BlendFactor";
import type { Blending } from "./Blending";

/**
 * How a pass's fragments reach the target, from the first pass's own fields.
 */
export type RenderState = { blending: Blending, 
/**
 * `StaticMaterialPassDef.srcColorBlendFactor`, defaulting to [`BlendFactor::One`].
 */
srcFactor: BlendFactor, 
/**
 * `StaticMaterialPassDef.dstColorBlendFactor`, defaulting to [`BlendFactor::Zero`].
 */
dstFactor: BlendFactor, 
/**
 * The pass multiplies its colour by its own alpha before blending.
 */
premultiplied: boolean, 
/**
 * The pass clips on a threshold it states itself and writes depth, so it draws
 * unblended and the depth buffer resolves it rather than a sort.
 */
cutout: boolean, 
/**
 * `cullEnable` is off, so both faces draw.
 */
doubleSided: boolean, 
/**
 * The pass culls the winding the engine keeps by default, which an inverted hull does.
 */
inverted: boolean, depthWrite: boolean, depthTest: boolean, };
