// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Define } from "./Define";
import type { PassParam } from "./PassParam";
import type { PassState } from "./PassState";
import type { PassTexture } from "./PassTexture";
import type { RuntimeSwitch } from "./RuntimeSwitch";
import type { ShaderSchema } from "./ShaderSchema";

/**
 * One `StaticMaterialPassDef` with its shader's inputs filled in.
 */
export type ResolvedPass = { 
/**
 * The pass shader's `objectPath`, which its TOCs are named after, and none where the
 * link resolves to nothing.
 */
shader: string | null, 
/**
 * The define list that picks the permutation, by name.
 */
defines: Array<Define>, 
/**
 * The switches the shader reads at run time, each the `$Globals` float
 * `switch_<name>`.
 */
runtimeSwitches: Array<RuntimeSwitch>, 
/**
 * Every shader texture in declaration order, each bound as `<name>__TX`.
 */
textures: Array<PassTexture>, 
/**
 * Every physical parameter in declaration order, each a `$Globals` member.
 */
params: Array<PassParam>, state: PassState, 
/**
 * What the pass shader declares, and none where the defs were not opened.
 */
schema: ShaderSchema | null, };
