// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a row copies as. Each half is absent where the row has no spelling for it: the object
 * row itself, a path through a field no table names, and a value holding such a field.
 */
export type RowDeclaration = { 
/**
 * An `entries` module setting the row to its value, as it stands under `modules`.
 */
declaration: string | null, 
/**
 * The row as a game-copy reference, `<entry>:<property path>`.
 */
reference: string | null, };
