// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a row sits in the tree.
 */
export type RowNode = "object" | "property" | "element" | "entry";
