// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stable id a user reads, such as `bin/property-type`.
 *
 * The first part names what the rule reads and the second names the state it
 * objects to. It is on every row, because an id is what a user pastes into a
 * search when they want to know more.
 */
export type RuleId = string;
