// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a rule speaks about a project, and what it waits for if not.
 *
 * A check about a change the installed game has not taken still runs, because
 * a modder wants to see what is coming. What it does not do is claim the mod
 * is broken today: the panel draws those findings muted and leaves them out
 * of the count in the project bar, and this is what tells it which they are.
 */
export type RuleState = { "kind": "active" } | { "kind": "dormant", 
/**
 * One sentence naming what it waits for, in the rule's own words.
 */
reason: string, };
