// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleId } from "./RuleId";
import type { RuleState } from "./RuleState";

/**
 * What one check is, apart from anything it found.
 *
 * Sent once per run rather than copied onto every row: a project can hold
 * thousands of problems and the words describing the check are the same on
 * each of them.
 */
export type RuleInfo = { id: RuleId, 
/**
 * A few words naming the state the rule objects to.
 */
title: string, 
/**
 * One sentence saying what that state is.
 */
description: string, 
/**
 * Why some of this rule's findings stay unrepaired, or empty where none do.
 */
unfixable?: string, 
/**
 * Whether this project is one the rule speaks about yet.
 */
state: RuleState, };
