// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemSeverity } from "./ProblemSeverity";
import type { TypeMismatch } from "./TypeMismatch";

/**
 * One rule's live findings, folded to what a mod user reads.
 *
 * A rule title and its counts, never a site or a property path - that is the
 * modder's half, and it lives in the Problems panel.
 */
export type RuleBrief = { 
/**
 * The rule's stable id, which the row quotes as a chip.
 */
rule: string, 
/**
 * A few words naming the state the rule objects to.
 */
title: string, 
/**
 * One sentence saying what that state is, which is the cause a reader
 * gets - sites and property paths stay in the Problems panel.
 */
description: string, 
/**
 * The worst this rule found here.
 *
 * Folded per problem rather than taken from the rule, since one rule can
 * report the same state at two severities.
 */
severity: ProblemSeverity, 
/**
 * Live findings from this rule.
 */
count: number, 
/**
 * How many of them a repair would fix.
 */
fixable: number, 
/**
 * The type pairs the findings disagree on, distinct and in first-seen
 * order. Where a rule reports types, `Expected File, found Hash` is the
 * actual problem, and the row draws it in place of the description.
 */
mismatches?: Array<TypeMismatch>, 
/**
 * Why the rest stay unrepaired, present only when some do.
 */
unfixable?: string, };
