// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleId } from "./RuleId";
import type { Site } from "./Site";

/**
 * A rule that could not finish, and why.
 */
export type RuleFailure = { rule: RuleId, 
/**
 * The file the rule stopped on, where one file is to blame.
 */
site: Site | null, message: string, };
