// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectInfo } from "./ObjectInfo";
import type { Problem } from "./Problem";
import type { RuleFailure } from "./RuleFailure";
import type { RuleInfo } from "./RuleInfo";

/**
 * One pass of every rule over one project.
 */
export type Run = { 
/**
 * When the run read the files.
 */
at: string, 
/**
 * Every check that ran, whether or not it found anything.
 */
rules: Array<RuleInfo>, 
/**
 * The name of every object a problem sits in, where a table holds one.
 */
objects: Array<ObjectInfo>, problems: Array<Problem>, 
/**
 * A rule that could not finish, and why. A run never fails as a whole.
 */
failed: Array<RuleFailure>, };
