// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A static switch the shader reads as a `$Globals` float rather than a define.
 */
export type RuntimeSwitch = { 
/**
 * The switch's name, without the `switch_` the member carries.
 */
name: string, on: boolean, };
