// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One combined sampler in the GLSL.
 */
export type SamplerBinding = { 
/**
 * The `RDEF` sampler name, or null for a texture read by `Load` alone.
 */
sampler: string | null, 
/**
 * The GLSL uniform to bind the texture unit to.
 */
glslName: string, };
