// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Wrap } from "./Wrap";

/**
 * How a texture is sampled: a shared sampler by name, or the entry's own modes.
 */
export type SamplerState = { 
/**
 * `ShaderTexture.samplerName`, the `X3DSharedSamplerDef` the shader reads through
 * as `<name>_SharedSampler`, which wins over the modes below.
 */
shared: string | null, 
/**
 * `addressU`, `addressV` and `addressW`.
 */
wrap: [Wrap, Wrap, Wrap], 
/**
 * `filterMin` is 1, linear.
 */
filterMin: boolean, 
/**
 * `filterMag` is 1, linear.
 */
filterMag: boolean, };
