// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which sandbox a document opens in, as it crosses IPC.
 */
export type SandboxRef = { "kind": "game" } | { "kind": "project", 
/**
 * The project directory.
 */
project: string, } | { "kind": "layer", 
/**
 * The project directory.
 */
project: string, 
/**
 * The layer's name.
 */
layer: string, };
