// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The status the scan reported, read once for every consumer.
 *
 * Carried on the [`Incident`] so a consumer can tell one rejection from
 * another without reading [`Verdict::cause`] as prose, and sent beside the raw
 * code on `patcher-wad-scan-failed` so the dialog keeps no second table.
 */
export type ScanStatus = "skinhack" | "missing-bin" | "corrupt" | "out-of-memory" | "base-skin" | "base-wad" | "unknown";
