// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `ShaderTexture` a `samplerValues` entry may name.
 */
export type SchemaTexture = { name: string, 
/**
 * `defaultTexturePath`, drawn where the material names no texture.
 */
default: string | null, 
/**
 * `samplerName`, the shared sampler that overrides a material's address modes.
 */
sharedSampler: string | null, };
