// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One name a `paramValues` entry may carry, with the value the shader holds for it.
 */
export type SchemaParam = { 
/**
 * The logical name, or the physical one where the parameter declares no logical names.
 */
name: string, 
/**
 * The physical parameter it writes into, which the `$Globals` member carries.
 */
physical: string, 
/**
 * `ShaderLogicalParameter.fields`, the components of the physical parameter the entry's
 * value writes, in order. 15 for a physical parameter written whole.
 */
fields: number, 
/**
 * The components `fields` selects out of the physical default, packed from the first,
 * which is the value an entry would hold to change nothing.
 */
default: [number, number, number, number], };
