// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `ShaderStaticSwitch` a `switches` entry may name.
 */
export type SchemaSwitch = { name: string, onByDefault: boolean, 
/**
 * Read as a `$Globals` float at run time, so a toggle recompiles nothing.
 */
runtime: boolean, };
