// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A watched session's phase moved.
 *
 * What the match is doing, and nothing about whether League is up - that
 * arrives as [`SessionGameRunning`].
 */
export type SessionChanged = { 
/**
 * The Riot Client's own spelling for the phase it moved to.
 */
phase: string, };
