// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Riot Client opened a session, at the phase it opened in.
 *
 * The first thing a watched session reports, and the point at which the
 * manager knows a launch produced something rather than merely being accepted.
 */
export type SessionStarted = { 
/**
 * The Riot Client's own spelling, e.g. `Pending` or `Gameplay`. Passed
 * through rather than mapped: a phase this build does not know is still
 * worth showing, and a label invented for it would not be.
 *
 * Read it as what the *match* is doing. It is not the test for whether
 * League is up - see [`SessionStarted::running`].
 */
phase: string, 
/**
 * Whether `LeagueClient.exe` is up.
 *
 * The fact the manager acts on, because it is when mods reach a game. The
 * phase does not answer it: a player sitting in the client reports phase
 * `None` with the process very much alive.
 *
 * False for the ordinary launch, where the client mints the session a few
 * seconds before the process appears, and true for a session adopted or
 * recovered under a game that was already running.
 */
running: boolean, 
/**
 * The content release the session is running, e.g. `24C2E5A086AFFB82` -
 * the client's own `version` field, which is a release id rather than the
 * patch number a player would recognise.
 */
version: string, };
