// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A watched session ended.
 *
 * Both fields are absent when the Riot Client exited and took the session
 * record with it while the game also stopped. That is a real ending with
 * nothing to say about why, and the frontend must not word it as a crash.
 */
export type SessionEnded = { 
/**
 * The game's exit code, as the client recorded it.
 */
exitCode: bigint | null, 
/**
 * The client's own termination reason, e.g. `Exit` or `Timeout`.
 */
exitReason: string | null, };
