// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The game appeared, or went away, during a live session.
 *
 * The event the status bar and the patcher care about. It arrives on a change
 * only - the reading at the moment the session opened rides on
 * [`SessionStarted::running`] instead.
 */
export type SessionGameRunning = { 
/**
 * Whether `LeagueClient.exe` is up.
 */
running: boolean, };
