// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaParam } from "./SchemaParam";
import type { SchemaSwitch } from "./SchemaSwitch";
import type { SchemaTexture } from "./SchemaTexture";

/**
 * The parameters, textures and switches a `CustomShaderDef` declares, with its defaults.
 *
 * A material's `paramValues`, `samplerValues` and `switches` override these by name, so
 * an editor lists every declared row and the material's value where it writes one.
 */
export type ShaderSchema = { 
/**
 * Every logical parameter, in declaration order.
 */
params: Array<SchemaParam>, 
/**
 * Every texture, in declaration order.
 */
textures: Array<SchemaTexture>, 
/**
 * Every static switch, in declaration order.
 */
switches: Array<SchemaSwitch>, };
