// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";
import type { TextureBinding } from "./TextureBinding";
import type { UniformBlock } from "./UniformBlock";

/**
 * What a translated stage binds.
 */
export type Sidecar = { blocks: Array<UniformBlock>, textures: Array<TextureBinding>, 
/**
 * Empty for a pixel shader.
 */
attributes: Array<Attribute>, };
