// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeAddress } from "./NodeAddress";

/**
 * Where a problem is.
 */
export type Site = { 
/**
 * The layer, such as `base`.
 */
layer: string, 
/**
 * The file, POSIX-style and relative to the layer root.
 */
path: string, 
/**
 * Where inside the file. `None` for a rule that reads a file as a whole.
 */
node: NodeAddress | null, };
