// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a property edit does not apply, as `ltk_game_data` names it.
 */
export type SkipReason = "missingObject" | "missingProperty" | "nullPointer" | "cannotDescend" | "notIndexable" | "indexOutOfRange" | "invalidKey" | "keyNotFound" | "typeMismatch" | "invalidPath" | "untypable" | "unknownClass" | "pinMismatch" | "signOnScalar" | "containerAbsent" | "removalUnmatched" | "kindMismatch" | "outOfRange" | "precisionLoss" | "arityMismatch" | "referenceMissingEntry" | "referenceUnresolved" | "unknown";
