// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterSpell } from "./CharacterSpell";

/**
 * The install's named spells for one character, without a search result cap.
 */
export type SpellCatalog = { 
/**
 * Spells in natural path order.
 */
spells: Array<CharacterSpell>, 
/**
 * Unnamed spell objects across the install, whose character cannot be established.
 */
unnamed: number, };
