// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissileSpec } from "./MissileSpec";
import type { SpellIssue } from "./SpellIssue";

/**
 * The spell's missile and flight-effect references before skin resolution.
 */
export type SpellPreview = { 
/**
 * The written `spellCastTime`, in seconds.
 */
spellCastTime: number | null, 
/**
 * The written `mCastTime`, kept separate from `spellCastTime`.
 */
castTime: number | null, 
/**
 * Whether the spell explicitly enables its hit effect.
 */
haveHitEffect: boolean | null, 
/**
 * The hit effect's skin resolver key.
 */
hitEffectKey: string | null, 
/**
 * The hit effect's written fallback name.
 */
hitEffectName: string | null, 
/**
 * The seven written display ranges, including rank zero.
 */
castRangeDisplay: Array<number> | null, 
/**
 * The seven legacy cast ranges, including rank zero.
 */
castRange: Array<number> | null, 
/**
 * The seven ranges in `castRangeValues.values`.
 */
castRangeValues: Array<number> | null, 
/**
 * The seven primary area radii.
 */
castRadius: Array<number> | null, 
/**
 * The seven secondary area radii.
 */
castRadiusSecondary: Array<number> | null, 
/**
 * The written cone angle in degrees.
 */
castConeAngle: number | null, 
/**
 * The written cone distance in engine units.
 */
castConeDistance: number | null, 
/**
 * The written animation-graph clip name, absent when the spell omits it.
 */
animationName: string | null, 
/**
 * The missile specification, absent for spells without one.
 */
missile: MissileSpec | null, 
/**
 * A resource key, never a system-object identity.
 */
effectKey: string | null, 
/**
 * The written fallback effect name, retained for inspection.
 */
effectName: string | null, 
/**
 * Fields requiring correction or an explicit preview approximation.
 */
issues: Array<SpellIssue>, };
