// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a missile field could not be used.
 */
export type SpellIssueKind = "invalid" | "unsupported";
