// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellIssueKind } from "./SpellIssueKind";

/**
 * A field the isolated preview cannot evaluate.
 */
export type SpellIssue = { 
/**
 * The named property path within the spell object.
 */
path: string, 
/**
 * Whether the field is malformed or needs an unimplemented behavior.
 */
kind: SpellIssueKind, };
