// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sidecar } from "./Sidecar";

/**
 * One translated stage of a program.
 */
export type StageProgram = { 
/**
 * The shader id the TOC lists the permutation under.
 */
id: number, glsl: string, sidecar: Sidecar, 
/**
 * The translation came off the disk cache rather than being made now.
 */
cached: boolean, };
