// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of `mSyncGroupDataMap`.
 */
export type SyncGroup = { name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * `mType`.
 */
kind: number, };
