// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What carries a system a template made, per ADR-0057.
 */
export type TemplateCarrier = "ground" | "flight" | "orbit";
