// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One emitter a template lands, with the name it is written under.
 */
export type TemplateEmitter = { 
/**
 * The English `emitterName` it holds, which a landing numbers apart from the system's.
 */
name: string, 
/**
 * The emitter as clipboard text.
 */
text: string, };
