// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateCarrier } from "./TemplateCarrier";
import type { TemplatePlayback } from "./TemplatePlayback";

/**
 * The rig a system template was tuned on.
 */
export type TemplateRig = { carrier: TemplateCarrier, playback: TemplatePlayback, 
/**
 * A flight's speed in engine units a second, and `None` for the carrier's own.
 */
speed: number | null, };
