// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SamplerBinding } from "./SamplerBinding";
import type { TextureDimension } from "./TextureDimension";

/**
 * One texture the shader samples, and the GLSL samplers that sample it.
 */
export type TextureBinding = { 
/**
 * The `RDEF` name, suffix and all: `Diffuse_Texture__TX`, `PIXEL_COLOR_REMAP_RAMP_SharedTexture`.
 */
name: string, dimension: TextureDimension, 
/**
 * A texture sampled by two samplers is two GLSL uniforms and costs two units.
 */
samplers: Array<SamplerBinding>, };
