// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which step of section 11.5 supplied a texture's path.
 */
export type TextureSource = "material" | "shaderDefault" | "fallback";
