// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a texture uniform is declared as.
 */
export type TextureDimension = "texture2d" | "texture2dArray" | "texture3d" | "cube" | "cubeArray" | "buffer" | "other";
