// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of `mTrackDataMap`.
 */
export type Track = { name: string, 
/**
 * The key, `0x` and eight hex digits.
 */
hash: string, 
/**
 * `mPriority`.
 */
priority: number, 
/**
 * `mBlendMode`.
 */
blendMode: number, 
/**
 * `mBlendWeight`.
 */
blendWeight: number, };
