// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A property whose declared type is not the one the game reads.
 *
 * The two types stay apart rather than arriving as one sentence, because a
 * panel sets each of them in code type inside prose it writes itself.
 */
export type TypeMismatch = { 
/**
 * The type the game reads, such as `file`, in the words a bin row's tag draws.
 */
expected: string, 
/**
 * The type the file declares, such as `string`.
 */
found: string, };
