// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockMember } from "./BlockMember";

/**
 * One uniform block, as the blob's `RDEF` laid it out.
 */
export type UniformBlock = { 
/**
 * The `RDEF` name: `$Globals`, `PerFrameVertexCB`.
 */
name: string, 
/**
 * The block name in the GLSL, which carries the stage suffix.
 */
glslName: string, 
/**
 * The buffer's size in bytes, a multiple of 16.
 */
size: number, members: Array<BlockMember>, };
