// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeafValue } from "./LeafValue";
import type { NewItem } from "./NewItem";

/**
 * One staged edit, addressed relative to its enclosing property.
 */
export type ValueEdit = { "type": "ensureProperty", path: string, field: string, } | { "type": "ensurePointer", path: string, class: string, } | { "type": "replacePointer", path: string, class: string | null, } | { "type": "insertItem", path: string, item: NewItem, } | { "type": "copyItem", from: string, path: string, index: number | null, unique: string | null, } | { "type": "pasteItem", path: string, index: number | null, text: string, unique: string | null, } | { "type": "removeItem", path: string, } | { "type": "setLeaf", path: string, value: LeafValue, };
