// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateEmitter } from "./TemplateEmitter";
import type { TemplateRig } from "./TemplateRig";
import type { VfxTemplateKind } from "./VfxTemplateKind";

/**
 * One template of the catalog.
 */
export type VfxTemplate = { 
/**
 * The catalog's key, which the frontend's messages are named by.
 */
id: string, kind: VfxTemplateKind, 
/**
 * The English name an emitter or a system made from it is written with.
 */
name: string, 
/**
 * The rig a system template was tuned on, and `None` for an emitter template.
 */
rig: TemplateRig | null, 
/**
 * The game patch the template was last checked on in game, and `None` for one not yet.
 */
checked: string | null, 
/**
 * The emitters the template lands, in list order: itself for an emitter template.
 */
emitters: Array<TemplateEmitter>, };
