// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a template is one emitter or a whole system.
 */
export type VfxTemplateKind = "emitter" | "system";
