// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanStatus } from "./ScanStatus";

/**
 * One archive that failed the integrity scan, sent in [`WadScanFailedPayload`].
 */
export type WadScanFailureInfo = { 
/**
 * The offending archive (e.g. `TahmKench.wad.client`), if its name parsed.
 */
wad: string | null, 
/**
 * The code the scan reported, an NTSTATUS-style one the game raised
 * (`c0000229`), or a word the DLL's own checks named (`mod_wad`).
 */
status: string, 
/**
 * What [`ScanStatus::parse`] makes of `status`, so the dialog reads a
 * rejection the way the Games tab does instead of keeping a second table.
 */
reading: ScanStatus, };
