// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The winding a pass culls, `windingToCull` on the wire.
 */
export type Winding = "cw" | "ccw";
