//! The chunks a built-in mod overrides, written as a mod project for the overlay to read.

use crate::error::AppResult;
use camino::{Utf8Path, Utf8PathBuf};
use fs_err as fs;
use ltk_mod_project::{ModProject, ModProjectAuthor, ModProjectLayer};
use std::borrow::Cow;
use std::collections::{BTreeMap, BTreeSet};
use std::io;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

/// The chunks a built-in mod overrides, by game archive and chunk path.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(super) struct Overrides {
    files: BTreeMap<Utf8PathBuf, Cow<'static, [u8]>>,
}

impl Overrides {
    /// Override `chunk_path` in the game archive named `wad` with `bytes`.
    pub(super) fn insert(
        &mut self,
        wad: &str,
        chunk_path: &str,
        bytes: impl Into<Cow<'static, [u8]>>,
    ) {
        self.files
            .insert(Utf8Path::new(wad).join(chunk_path), bytes.into());
    }

    /// Each override by its path below the layer, `<wad>/<chunk path>`, in path order.
    pub(super) fn iter(&self) -> impl Iterator<Item = (&Utf8Path, &[u8])> {
        self.files
            .iter()
            .map(|(path, bytes)| (path.as_path(), bytes.as_ref()))
    }

    /// Write the overrides to `dir` as the `base` layer of the mod project `name`.
    ///
    /// Only a file whose bytes differ is rewritten, since an unchanged file keeps the
    /// modification time the overlay's content fingerprint reads. A file an earlier write left
    /// that the overrides no longer hold is removed, and nothing outside the layer is touched.
    ///
    /// # Errors
    ///
    /// Fails when a file cannot be read, written or removed.
    pub(super) fn write(&self, dir: &Path, name: &str, display_name: &str) -> AppResult<()> {
        let layer_dir = dir.join("content").join(ModProjectLayer::BASE_NAME);
        fs::create_dir_all(&layer_dir)?;
        write_if_changed(
            &dir.join("mod.config.json"),
            &serde_json::to_vec_pretty(&mod_project(name, display_name))?,
        )?;

        let mut kept = BTreeSet::new();
        for (path, bytes) in self.iter() {
            let path = layer_dir.join(path);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            write_if_changed(&path, bytes)?;
            kept.insert(path);
        }
        remove_all_but(&layer_dir, &kept)
    }
}

fn mod_project(name: &str, display_name: &str) -> ModProject {
    ModProject {
        name: name.to_owned(),
        display_name: display_name.to_owned(),
        version: "1.0.0".to_owned(),
        description: "Generated by LTK Manager.".to_owned(),
        authors: vec![ModProjectAuthor::Name("LTK Manager".to_owned())],
        license: None,
        tags: Vec::new(),
        champions: Vec::new(),
        maps: Vec::new(),
        transformers: Vec::new(),
        layers: ModProjectLayer::default_table(),
        thumbnail: None,
        hashtables: Vec::new(),
    }
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> AppResult<()> {
    if fs::read(path).is_ok_and(|current| current == bytes) {
        return Ok(());
    }
    fs::write(path, bytes)?;
    Ok(())
}

/// Remove every file under `dir` outside `kept`, and each directory that leaves empty.
fn remove_all_but(dir: &Path, kept: &BTreeSet<PathBuf>) -> AppResult<()> {
    for entry in WalkDir::new(dir).min_depth(1).contents_first(true) {
        let entry = entry.map_err(io::Error::from)?;
        if entry.file_type().is_dir() {
            if fs::read_dir(entry.path())?.next().is_none() {
                fs::remove_dir(entry.path())?;
            }
        } else if !kept.contains(entry.path()) {
            fs::remove_file(entry.path())?;
        }
    }
    Ok(())
}
